### ISSUE TITLE
sys-devel/llvm-roc-2.0.0 should depend on virtual/cblas-1.0

### ISSUE THREAD

**Issue by ernsteiswuerfel** [justxi/rocm#10]
[...]
CMake Error at cmake/modules/AddLLVM.cmake:459 (add_library):
  Cannot find source file:

    /usr/include/cblas.h
[...]

[llvm-roc-2.0.0:20190124-132403.log](https://github.com/justxi/rocm/files/2793318/llvm-roc-2.0.0.20190124-132403.log)

**Comment by justxi** [comment]
Thanks for the hint, I will check this.

**Comment by justxi** [comment]
But please keep in mind, all version 2.0 related ebuilds, which are not in official Gentoo portage are in experimental state.

**Comment by ernsteiswuerfel** [comment]
I do. ;) And thanks for your work!

**Comment by justxi** [comment]
=)
Added the dependency, closing this.
