### ISSUE TITLE
Can't build rocm-device-libs-3.0.0

### ISSUE THREAD

**Issue by 2l42h3r** [justxi/rocm#110]
Attempting to build rocm-opencl-runtime-3.0.0, getting errors at compile time with rocm-device-libs-3.0.0.

Emerge --info and build log attached.
[emerge-info-rocm-device-libs-3.0.0.txt](https://github.com/justxi/rocm/files/4008134/emerge-info-rocm-device-libs-3.0.0.txt)
[rocm-device-libs-3.0.0-build.log](https://github.com/justxi/rocm/files/4008135/rocm-device-libs-3.0.0-build.log)

**Comment by justxi** [comment]
Some thoughts... 

Due to "Could NOT find ROCM (missing: ROCM_DIR)" , do you have "dev-util/rocm-cmake" installed?

You have a lot of additional flags set - Could you try with:
```
Compiler flags:
C               -march=native -O2 -pipe
C++             -march=native -O2 -pipe
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed
```
With this flags it builds on my system.

**Comment by 2l42h3r** [comment]
One-shotting rocm-cmake didn't solve the issue, neither did reemerging rocm-device-libs with more vanilla flags. What did solve the problem tough was rebuilding most of the dependency tree with safe (-O2, -march=native, -pipe) flags (I suspect llvm-roc to be the culprit).

rocm-cmake is required for building rocm-opencl-runtime itself, but it doesn't get pulled automatically, so that's one thing that could be changed in the ebuild.

**Comment by justxi** [comment]
Ok, thanks for the information.
