### ISSUE TITLE
Installation...

### ISSUE THREAD

**Issue by ScarFez** [justxi/rocm#122]
Is it possible to get a quick how-to for people like me who just want a way to run OpenCL empowered applications ?

I've been trying to install rocm for most of the year now and I have yet to succeed...

**Comment by justxi** [comment]
If you are using Gentoo Linux you can emerge "rocm-opencl-runtime", this should build all what you need to use ROCm based OpenCL.

**Comment by ScarFez** [comment]
is there a binary package or some sort of app image, or even a script that can install gentoo in such a way it will be compatible with rocm ?
I'm having some major issues building rocm-opencl-runtime
Not sure if it's because of my version of llvm or something else...
Thanks

**Comment by ScarFez** [comment]
It fails on rocm-opencl-driver, it can't be built (2.10.0)

**Comment by justxi** [comment]
You can read the ebuilds, there you find the parameters for cmake.

There are also binaries from AMD, which you can install. 
Look at "amd-rocm-meta-bin" in "dev-util".

**Comment by ScarFez** [comment]
There is no amd-rocm-meta-bin in the gentoo portage

Chances are you have some sort of overlay and it's actually from 
somewhere else.. not from amd, that's for sure, they wouldn't support 
linux unless windows disappears for some magic reason and there is no 
other choice.

**Comment by justxi** [comment]
You are kidding me, right?
