### ISSUE TITLE
rocminfo not working since libhsa-runtime64.so not found

### ISSUE THREAD

**Issue by davidrohr** [justxi/rocm#13]
Hi, I started to test the tools, and already rocminfo fails.
The first problem is that dev-libs/rocr-runtime-2.0.0 installs libhsa-runtime64.so to /usr/lib/hsa, but that is not in the LD_LIBRARY_PATH.

**Comment by justxi** [comment]
Ok, I think a quick solution is to create symlinks...

**Comment by davidrohr** [comment]
I do not really like symlinks. I'd sugest either we change the install directory direcly to /usr/lib instead of /usr/lib/hsa, or we set up the LDPATH in gentoo properly by adding the following lines to src_install:
`        echo "HSA_PATH=/usr/lib" >> 99hsa || die
        echo "LDPATH=/usr/lib/hsa" >> 99hsa || die
        doenvd 99hsa
`

**Comment by justxi** [comment]
I changed the patch-file in my respository: https://github.com/justxi/rocm/tree/master/dev-libs/rocr-runtime, now the library and correspoinding symlinks should be in /usr/lib64

**Comment by davidrohr** [comment]
Thanks, that works for me
