### ISSUE TITLE
Everything should be installed in /opt

### ISSUE THREAD

**Issue by Lucretia** [justxi/rocm#134]
I have been speaking to an amd guy on irc about this and trying to get everything built with hip.

He said the following:

> in no way should this be installed to /usr
> pretty much everything assumes installation in /opt/rocm
> recently there's been some cleanup to make things better behaved so at least /opt/rocm-version can exist side by side

**Comment by justxi** [comment]
We spent a lot of effort to install according to FHS. So you could proof if it is working if you use the binaries, see dev-util/amd-rocm-meta-bin. If it works then we could try to find the reason why it is not working with our ebuilds.

**Comment by RarogCmex** [comment]
Yes, I also works many times to add FHS in AMDVLK https://bugs.gentoo.org/665590

**Comment by justxi** [comment]
If you want to discuss any issues regarding this, please reopen.
