### ISSUE TITLE
conflicts between dev-libs/rocm-device-libs and rocm-opencl-runtime-2.0.0

### ISSUE THREAD

**Issue by stalkerg** [justxi/rocm#14]
rocm-opencl-runtime depend on rocm-device-libs but they install same files.

**Comment by justxi** [comment]
Yes, I plan to create an additional ebuild, but it is not as easy as I thought. So I included the device libs temporary.

**Comment by justxi** [comment]
I uploaded a new ebuild which blocks "rocm-device-libs".
