### ISSUE TITLE
Kernel module for 5.4 LTS kernel

### ISSUE THREAD

**Issue by MageSlayer** [justxi/rocm#141]
Hi

I might be very wrong in my expectations, but can't ROC kernel module be built separately against vanilla 5.4.* kernels?

Should it work at all like that?

**Comment by justxi** [comment]
I did´t try it. I am using the kernel built from "gentoo-sources".

**Comment by MageSlayer** [comment]
I haven't got you.
Did you try building ROC module against gentoo-sources, or you didn't?

**Comment by justxi** [comment]
No I didn`t.
I use only the gentoo-sources without any additional modules.

**Comment by MageSlayer** [comment]
Ok.
Then I don't get how you build ROC module against gentoo-sources.
Do you have any separate ebuild for module only besides rocm-sources?

**Comment by justxi** [comment]
No, I didn´t found the sources for the kernel module.

**Comment by MageSlayer** [comment]
Hm.
I am getting following:
```
~ $ sudo rocminfo 
ROCk module is NOT loaded, possibly no GPU devices
```
That's why I thought some extra module is expected.

Could you share your kernel settings for gentoo-sources?

**Comment by justxi** [comment]
If you get this information, maybe you have compiled the module into the kernel?

**Comment by MageSlayer** [comment]
I wish I knew which module is that.
Shouldn't rocminfo be happy with compiled-in module?

**Comment by justxi** [comment]
Yes it should.

**Comment by MageSlayer** [comment]
Ok. I got it.
It's just misleading error message!
That rocminfo just stubbornly looks for amdgpu among modules! 
If amdgpu is compiled in kernel, it just emits that error!
https://github.com/RadeonOpenCompute/rocminfo/blob/1a81ee3eb9fdd9d30ede71b5e344410fa7df5356/rocminfo.cc#L1027

Running clinfo shows that everything is place and works fine.
Sorry for noise.

**Comment by justxi** [comment]
No problem.
