### ISSUE TITLE
Exclusiveness of gfx architecture flags

### ISSUE THREAD

**Issue by aclex** [justxi/rocm#142]
I've started preparing [Docker image](https://hub.docker.com/r/aclex/gentoo-rocm) for ROCm on top of official stage3 Gentoo image  and come across the question of how to deal with GPU architecture flags. Now they are exclusive in all packages I've checked, i.e. only one flag may be enabled. This is probably good in terms of the spirit of Gentoo, that the package is as optimized and specified for certain hardware, as possible. On the other hand, official and other ROCm images are for all architectures at once, which reduces the confusion (and choice) for the user (they just pull the only image per ROCm version) and build time and resources for maintainer (it takes about 12 hours for me to build the image, including 2-3 hours when I can't use the computer at all due to all the RAM eaten by the rocBLAS building).

So I don't know the right answer here, wanted to discuss it now during version 3.3 being stabilized, in case of maybe remove the exclusiveness requirement from packages if would be so decided as a better way.

**Comment by justxi** [comment]
Thats a good idea. 
As far as I understand it, at least in the past, the architecture was detected automatically.
I added the patches to select one architecture, because the autodetection failed due to the ebuild.
The build scripts (cmake) from AMD seem to support multiple architecture. 

I added a possibility to "rocm_agent_enumerator" (https://github.com/RadeonOpenCompute/rocminfo/blob/master/rocm_agent_enumerator) to set an environment variable, but had no time to test this. This could be an option to set multiple architecture within the build environment.

**Comment by aclex** [comment]
Yes, I'll also try to test the packages, if they are building fine with all the architectures enabled (by manual editing the ebuilds for now). At the moment I can just confirm, that `sci-libs/rocBLAS` works fine with all the architectures on, just because it ignores USE flags configuration and enables all the architectures in the CMakeLists.txt, possibly due to code changes. I wanted to fix it, but due to the size of the package it takes so long to test, if everything builds fine. So now it always builds for all architectures at once.

**Comment by justxi** [comment]
Can you create a PR with your changes?
I have to rebuild rocBLAS due to another problem. Then I could build it only once.

**Comment by aclex** [comment]
@justxi sure, here it is: #144. I haven't tested it thoroughly though, only several configuration runs, but obviously this should work. As I said, without this changes it builds `rocBLAS` for all architectures at once (namely, the list is: `gfx803;gfx900;gfx906;gfx908`).

**Comment by justxi** [comment]
Maybe I miss understood that, but first I thought that you want to build all architectures at once?

**Comment by aclex** [comment]
Yes, that's exactly right. I just mentioned, that `rocBLAS` is already being built this way due to inconsistency in configuration and obviously works successfully. I also said, that initially I wanted to fix it to be as GPU architecture specific, as the rest of the packages, but hadn't tested it to build. So I thought, you were interested in this particular fix, which is indeed to the opposite of what we're discussing here.

**Comment by aclex** [comment]
So yes, to make `rocBLAS` build for all the architectures at once no change needed at the moment, it's being built so out of the box now.

**Comment by justxi** [comment]
But it seems that my patches could be removed?

**Comment by aclex** [comment]
Do you mean Tensile-related patches in the ebuild? I don't really know, I haven't removed them during the build. I just noticed, that the package itself (kernels, etc.) is built against all possible GPU architectures.

**Comment by justxi** [comment]
Ok, I tried it, but I seems not to work.

I have added and extended your suggesstion to a new test ebuild: https://github.com/justxi/rocm/blob/master/sci-libs/rocBLAS/rocBLAS-3.3.0-r1.ebuild

**Comment by aclex** [comment]
Nice, thank you for trying it and collecting the results in the 3.3.0 ebuild, I think, that's fine for now. As for the case of all architectures, it would obviously require some additional testing. As we can see, the vanilla build tends to still auto-detect the particular GPU architecture, so it's unknown, how they manage to create a unified package for their Docker images.

**Comment by justxi** [comment]
That is not magic... =)
https://github.com/RadeonOpenCompute/rocminfo/blob/1a81ee3eb9fdd9d30ede71b5e344410fa7df5356/rocm_agent_enumerator#L62

AMD creates a file for it, that is what I am trying also... but rocm_agent_enumerator reads the file from the path where it is installed... that does not work in an ebuild... therefor I added the environment variable... (AMD accepted it), but setting an env var in the ebuild seems not work... I am currently trying a new idea..

**Comment by aclex** [comment]
Ah, OK, that's a list as well. I thought it's a single value, that either auto-detected or written manually, as in the ebuild.  Now it's quite clear. So theoretically it's possible to populate both `ROCM_TARGET_LST` and `AMDGPU_TARGETS` with all the architectures to get a package for all of them or specify one in both lists for architecture-specific build.

**Comment by justxi** [comment]
I updated the 3.3-r1 ebuild for rocBLAS now it works for me without my patches. GPU architecture can be detected using ROCM_TARGET_LST env var. Next step is to add more architectures and clean up the ebuild.

**Comment by aclex** [comment]
Thank you! Hope to try it while building 3.3 package versions, now it should be faster with the container image working recipe.

**Comment by justxi** [comment]
I updated the ebuild to be able to use all architectures... 
And I found another parameter where you can set a specific architecture for tensile https://github.com/justxi/rocm/blob/f7e2ac3ab5db956899baae594db6943f5c6a5ace/sci-libs/rocBLAS/rocBLAS-3.3.0-r1.ebuild#L106
This speeds up building rocBLAS a lot, instead of 50 minutes it takes only 6 minutes on my system.

**Comment by aclex** [comment]
Oh, well done, nice finding! Have you noticed if RAM utilization is also reduced? That's the bigger concern for me, as on previous version of ebuild rocBLAS builds for about two hours on my machine, including about an hour I have to refuse working at the PC as it's swapped to disk completely. The build time itself isn't that much an issue.

**Comment by justxi** [comment]
It seems that the usage of RAM is also reduced. I was able to use my PC the whole time, which is not possible when I built for all architectures.

**Comment by aclex** [comment]
Very nice and promising, will definitely try it while building the container image next time.
So for the case of per-architecture build there's only rocFFT package which takes much time to be built, while thanks to your previous suggestion it doesn't eat all of my RAM anymore when being compiled in one job. So overall in terms of ease of container preparation per-architecture way now looks doable as well.

**Comment by justxi** [comment]
I also added a "tensile" use flag. This, if not set, skips building of tensile. This leads to problem with depending packages, but I save a lot of compilation time also. So it is good for testing the ebuild.

**Comment by aclex** [comment]
Thank you! That indeed would be very handy for debugging purposes.

**Comment by justxi** [comment]
I think this is all done for the moment. In case not, please reopen.

**Comment by aclex** [comment]
Yes, I agree, thank you!
