### ISSUE TITLE
Reduction tests from HIP-Examples are failing

### ISSUE THREAD

**Issue by aclex** [justxi/rocm#145]
As I've mentioned in #133, there's some strange issue with global function linking in PyTorch built with ROCm enabled (https://github.com/ROCmSoftwarePlatform/pytorch/issues/572) and while investigating it @s-bernard have pointed me out on failure of reduction tests from [HIP-Examples](https://github.com/ROCm-Developer-Tools/HIP-Examples). I tried it on my installation of version 3.0 and it turned out to be reproducible. As @s-bernard says, this can be solved by not stripping the binary, but it's unclear, what it is in terms of packages here in Gentoo ROCm stack. `hipcc` seems to be just a Perl wrapper for `clang`, so obviously, it needs some more experimenting. On the other hand, it's unclear, if these tests failure lead to anything and this global function linking error in particular (obviously not).

**Comment by justxi** [comment]
I had a problem with the rocBLAS library, after setting RESTRICT="strip" the problem was solved.
So you mean, hip should also get the restriction?

**Comment by aclex** [comment]
I don't know for sure as haven't experimented with this tests failure myself yet, but I guess it is. I'll try to find out, what the exact binary cause this issue when stripped.

**Comment by aclex** [comment]
@justxi I've just experimented with it and can confirm, that the package in question is `sys-devel/hip` and yes, when built with `RESTRICT="strip"` it indeed let the reduction tests from HIP-Examples pass and without this (i.e. with stripping enabled) these reduction tests fail. There's also one test (`b+tree` from Rodinia suite) which fails in both cases. All the rest of the tests are passed in both cases. Here's the full output of the tests on two builds of `sys-devel/hip` on my system: https://gist.github.com/aclex/5349be5f13ea1892b409e43c645c57ca

**Comment by justxi** [comment]
Ok, if you like, you could add RESTRICT="strip" to the ebuild an create a PR.

**Comment by aclex** [comment]
It seems to be only partial solution, as there're other tests reportedly failing due to unknown reasons, but yes, I think, I'll do this.

**Comment by justxi** [comment]
Better a partial solution than nothing =).

**Comment by aclex** [comment]
Oh yes, indeed) Since this particular case seems to solved, I'll close this issue for now.
