### ISSUE TITLE
OpenGL + ROCm does not seem to work

### ISSUE THREAD

**Issue by MageSlayer** [justxi/rocm#146]
Hi 

Trying to use ROCm OpenCL together with Mesa OpenGL results in following (in my self-made application):
```
mesa: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```
According to numerous links in google it might be related to different LLVM versions used by Mesa & ROCm. I could not found any working receipt to make them work however.

Some people suggest building/linking static LLVM (https://github.com/justxi/rocm/issues/8#issuecomment-551017447), but looks like llvm-roc does not do that currently.

Tested under Mesa-19.3.5,9999 (opencl flag disabled) and rocm-opencl-runtime-3.3.0

Any help?

**Comment by justxi** [comment]
Yes, I have the same information, that the use of different llvm versions results in problems. At least using OpenCL of Mesa and Rocm-OpenCL-Runtime side by side. I hope that AMD upstreams all changes, so that "system" llvm/clang could be used. I don´t have used OpenGL for my AMD GPUs.
So, you could try to build mesa using llvm-roc.

**Comment by MageSlayer** [comment]
My quickly hacked mesa patch builds fine, but opencl stops working entirely :)
https://gist.github.com/MageSlayer/da203ba6a06719f1bbedf349cfa63b08

**Comment by justxi** [comment]
No output from "clinfo"?

**Comment by MageSlayer** [comment]
Yes. Empty output.
After rebuilding rocm-opencl-runtime it's back to "normal" (CL works without GL), Mesa GL + OpenCL still fails with the same error.

**Comment by justxi** [comment]
@candrews Do you know something about getting OpenCL and OpengGL to work for AMD GPUs?

**Comment by justxi** [comment]
@MageSlayer If you build Mesa and ROCm-OpenCL-Runtime both with "llvm-roc", can you use OpenCL and OpenGL separately?

**Comment by MageSlayer** [comment]
Yes.

**Comment by justxi** [comment]
So OpenGL works too, when compiled with "llvm-roc"?

**Comment by MageSlayer** [comment]
Yeap.

**Comment by MageSlayer** [comment]
Same issue with rocm-opencl-runtime-3.5.0

**Comment by MageSlayer** [comment]
Yes. The bug is still there.

**Comment by justxi** [comment]
I have currently no time to look at this issue.
Please reopen if you have new informations or solved it.
