### ISSUE TITLE
media-libs/hsa-amd-aqlprofile-1.0.0 failed to install

### ISSUE THREAD

**Issue by pepepper** [justxi/rocm#148]
>>> Install media-libs/hsa-amd-aqlprofile-1.0.0 into /var/tmp/portage/media-libs/hsa-amd-aqlprofile-1.0.0/image/
!!! dolib: /var/tmp/portage/media-libs/hsa-amd-aqlprofile-1.0.0/work/opt/rocm/hsa-amd-aqlprofile/lib/libhsa-amd-aqlprofile64.so.1.0.0 does not exist

I checked library name and found the name was changed to "libhsa-amd-aqlprofile64.so.1.0.30300"

**Comment by justxi** [comment]
Thanks for the information.
Should be fixed now.
