### ISSUE TITLE
hip 3.5.1 : hcc deprecated

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#151]
hcc deprecated !

please use hipcc instead hcc
and instead obsolete hcc platform use rocclr in all ebuilds

and bump hip to last version 3.5.1

**Comment by justxi** [comment]
I am working on this... =)

I have ebuilds to install "hip" based on rocclr from AOMP ... see https://github.com/justxi/rocm/issues/150 

I want to check if this HIP installation is usable for all the HIP libraries.

Maybe you give it a try?

**Comment by perestoronin** [comment]
> I am working on this... =)
> 
> I have ebuilds to install "hip" based on rocclr from AOMP ... see #150
> 
> I want to check if this HIP installation is usable for all the HIP libraries.
> Maybe you give it a try?
AOMP compliance with TF rocm revision or exists Tensorflow for AOMP ?

also you can adopt my vision on hip based on rocm from my first public version  
https://github.com/perestoronin/rocmnew/tree/master/sys-devel/hip

**Comment by justxi** [comment]
I don´t know it TF works with the AOMP stuff.
I thought, that AOMP it is needed for the rocclr based HIP.
But if HIP works with llvm-roc, then this makes it easier to update my "rocm" repository.
Sure, I will check your ebuild.

**Comment by perestoronin** [comment]
`# eix -Ic sci-libs/roc*
[I] sci-libs/rocBLAS (3.5.0-r1(0/3.5)[2]@20.06.2020): AMD's library for BLAS on ROCm
[I] sci-libs/rocFFT (3.5.0-r1(0/3.5)[2]@20.06.2020): Next generation FFT implementation for ROCm
[?] sci-libs/rocPRIM (3.5.1(0/3.5)[2]@20.06.2020 -> 3.5.0(0/(ver_cut 1-2))[2]): HIP parallel primitives for developing performant GPU-accelerated code on AMD ROCm platform
[I] sci-libs/rocSOLVER (3.5.0-r1(0/3.5)[2]@21.06.2020): Implementation of a subset of LAPACK functionality on the ROCm platform
[I] sci-libs/rocSPARSE (3.5.0-r1(0/3.5)[2]@21.06.2020): Common interface that provides Basic Linear Algebra Subroutines for sparse computation
[I] sci-libs/rocThrust (3.5.0(0/3.5)[2]@21.06.2020): ROCm Thrust - run Thrust dependent software on AMD GPUs
[1] "rocm" /usr/overlays-ext/rocm
[2] "rocmnew" /usr/overlays/rocmnew
`

**Comment by justxi** [comment]
I checked all the libraries and there are only a few updates from 3.5.0 to 3.5.1 =).

**Comment by perestoronin** [comment]
tag 3.5.1 for minor bug fix

**Comment by justxi** [comment]
Most of the ebuilds are upated already in Gentoo portage.
"rocm-device-libs" was missing, but I created a PR already.

**Comment by justxi** [comment]
> also you may attempt adopt my vision of hip based on rocm from my first public version
> https://github.com/perestoronin/rocmnew/tree/master/sys-devel/hip

I updated my ebuild with your changes.
But enabling "hipify" results in an error on my system. 
Does it work for you?

**Comment by perestoronin** [comment]
> But enabling "hipify" results in an error on my system.
> Does it work for you?
hipify for cuda, I think TF work with cuda excellent and without hip. 
I mask hipify take over errors for hip-cuda.
PS. Flag hipify may be usefull to translate cuda software to hip.

**Comment by justxi** [comment]
When I enable "hipify" cmake complains a missing directory. 
I remove the "+" from the use flags until this is fixed.

I wanted to compile "rccl" with hipcc, but it complains about missing bitcode (*.bc) files. 
They are all in "/usr/lib64". 
Does "hipcc" work on your system?
Where have you installed the bitcode files?

**Comment by justxi** [comment]
... and using the HIP installation I get the following error:
```
CMake Error in library/CMakeLists.txt:
  Imported target "hip::device" includes non-existent path

    "/usr/lib64/hip/3.5/../include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

Did you have the problem too?

**Comment by justxi** [comment]
The problems are fixed now =).

**Comment by perestoronin** [comment]
> I wanted to compile "rccl" with hipcc, but it complains about missing bitcode (*.bc) files.
> They are all in "/usr/lib64".
> Does "hipcc" work on your system?
> Where have you installed the bitcode files?

hipcc --version
HIP version: 3.5.20246-
clang version 11.0.0 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/roc/3.5/bin

/usr/lib # ls *.bc
hc.amdgcn.bc                               oclc_daz_opt_on.amdgcn.bc        oclc_isa_version_700.amdgcn.bc  oclc_isa_version_810.amdgcn.bc  oclc_unsafe_math_off.amdgcn.bc
hip.amdgcn.bc                              oclc_finite_only_off.amdgcn.bc   oclc_isa_version_701.amdgcn.bc  oclc_isa_version_900.amdgcn.bc  oclc_unsafe_math_on.amdgcn.bc
ockl.amdgcn.bc                             oclc_finite_only_on.amdgcn.bc    oclc_isa_version_702.amdgcn.bc  oclc_isa_version_902.amdgcn.bc  oclc_wavefrontsize64_off.amdgcn.bc
oclc_correctly_rounded_sqrt_off.amdgcn.bc  oclc_isa_version_1010.amdgcn.bc  oclc_isa_version_801.amdgcn.bc  oclc_isa_version_904.amdgcn.bc  oclc_wavefrontsize64_on.amdgcn.bc
oclc_correctly_rounded_sqrt_on.amdgcn.bc   oclc_isa_version_1011.amdgcn.bc  oclc_isa_version_802.amdgcn.bc  oclc_isa_version_906.amdgcn.bc  ocml.amdgcn.bc
oclc_daz_opt_off.amdgcn.bc                 oclc_isa_version_1012.amdgcn.bc  oclc_isa_version_803.amdgcn.bc  oclc_isa_version_908.amdgcn.bc  opencl.amdgcn.bc

On my systems rccl and rocALUTION does not compiled with same errors.

**Comment by perestoronin** [comment]
> The problems are fixed now =).

Thanks, I will try again to compile rccl and rocALUTION

**Comment by justxi** [comment]
If you have workings ebuilds feel free to create a PR.
