### ISSUE TITLE
Filesize does not match recorded size rocBLAS-3.5.0.ebuild

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#154]
* rocm/sci-libs/rocBLAS/rocBLAS-3.5.0.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 3319
 * Expected: 3267

**Comment by justxi** [comment]
I correct this, but the ebuild is currently only working without tensile. I need to fix this. Hopefully in the coming days.

**Comment by perestoronin** [comment]
Preferable use external Tensile version 3.5.0 

https://github.com/perestoronin/rocmnew/blob/master/dev-util/Tensile/Tensile-3.5.0.ebuild

**Comment by justxi** [comment]
Ok, I will try that.
