### ISSUE TITLE
bump rocm to version 3.6.0

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#155]
Please update rocclr, hip ... to version 3.6.0.

**Comment by justxi** [comment]
Thanks for the hint... I do will do at as soon as possible...

**Comment by justxi** [comment]
ROCm 3.6 is not officially released yet, right?

**Comment by perestoronin** [comment]
> ROCm 3.6 is not officially released yet, right?

Yes, in beta status.

**Comment by perestoronin** [comment]
prepare bump to 3.6.0 in https://github.com/perestoronin/rocmnew/commit/bea5af7b40f45a66303aad1deaeae743263a7ec6

**Comment by perestoronin** [comment]
finely bumped https://github.com/perestoronin/rocmnew to 3.6.0
but... amd hide hip and rocclr version 3.6.0 from public access, but I wgeted all before closed it.

**Comment by justxi** [comment]
I will update it, when AMD releases the final versions.
Again feel free to create PRs.
