### ISSUE TITLE
Install media-libs/hsa-amd-aqlprofile-1.0.0 failed

### ISSUE THREAD

**Issue by schuler-m** [justxi/rocm#156]
The installation failed with output:

_!!! Fetched file: hsa-amd-aqlprofile_1.0.0_amd64.deb VERIFY FAILED!_
_!!! Reason: Filesize does not match recorded size_
_!!! Got:      68922_
_!!! Expected: 68902_
_Refetching... File renamed to '/var/cache/distfiles/hsa-amd-aqlprofile_1.0.0_amd64.deb._checksum_failure_.ic1huj5a'_

_!!! Couldn't download 'hsa-amd-aqlprofile_1.0.0_amd64.deb'. Aborting._

**Comment by justxi** [comment]
It seems, that the file has changed.
I will check this and update the manifest.

**Comment by schuler-m** [comment]
Thanks, after I updated the local manifest file l got an other error:

_>>> Install media-libs/hsa-amd-aqlprofile-1.0.0 into /var/tmp/portage/media-libs/hsa-amd-aqlprofile-1.0.0/image/_
_!!! dolib: /var/tmp/portage/media-libs/hsa-amd-aqlprofile-1.0.0/work/opt/rocm-3.3.0/hsa-amd-aqlprofile/lib/libhsa-amd-aqlprofile64.so.1.0.30300 does not exist_
_ * ERROR: media-libs/hsa-amd-aqlprofile-1.0.0::rocm failed (install phase):_
_ *   dolib failed_

**Comment by schuler-m** [comment]
emerge --info '=media-libs/hsa-amd-aqlprofile-1.0.0::rocm'
[emerge_info.txt](https://github.com/justxi/rocm/files/4930888/emerge_info.txt)

**Comment by justxi** [comment]
Thanks for the information. I will add this.

**Comment by justxi** [comment]
It should be fixed by this PR https://github.com/justxi/rocm/pull/157.
If not please reopen.
