### ISSUE TITLE
hsa-amd-aqlprofile: incorrect SRC_URI

### ISSUE THREAD

**Issue by nethershaw** [justxi/rocm#161]
https://github.com/justxi/rocm/blob/67a4efca3d84d8898ba1b5a3ec21a40258b27b49/media-libs/hsa-amd-aqlprofile/hsa-amd-aqlprofile-3.5.0.ebuild#L9

This SRC_URI returns HTTP 404.

Correction:

```diff
-SRC_URI="http://repo.radeon.com/rocm/apt/debian/pool/main/h/hsa-amd-aqlprofile3.5.0/hsa-amd-aqlprofile3.5.0_1.0.0_amd64.deb"
+SRC_URI="https://repo.radeon.com/rocm/apt/3.5/pool/main/h/hsa-amd-aqlprofile3.5.0/hsa-amd-aqlprofile3.5.0_1.0.0_amd64.deb"
```

**Comment by justxi** [comment]
Ok, thanks for the hint.
I will update it.

**Comment by justxi** [comment]
Should be fixed now.
