### ISSUE TITLE
Cannot run tensorflow, possible gfx906/Vega 20 issue

### ISSUE THREAD

**Issue by pshirshov** [justxi/rocm#169]
I have Radeon VII, so I've built all the `3.7.0` packages with `gfx906` instead of `gfx803`.

I can build and successfully run HIP examples, though I cannot run any simple tensorflow script under `tensorflow-rocm==2.3.0`.

At the same time everything works fine with official Ubuntu packages. I'll add more details/diagnostics later.

UPD:

My test script:

```bash
#!/bin/bash -xe

hipconfig --full
rocminfo 

python -m venv venv

source ./venv/bin/activate

echo "
Keras==2.4.3
tensorflow-rocm==2.3.0
" > pip.txt

pip install -r pip.txt

echo "
import tensorflow as tf
print(tf.add(1, 2).numpy())
hello = tf.constant('Hello, TensorFlow!')
print(hello.numpy())
" > test.py


echo "TFTEST"
python test.py || true

echo "TFTEST+STRACE"
strace python test.py
```

The output:

[tftest.log](https://github.com/justxi/rocm/files/5239038/tftest.log)

The output of `eix --in-overlay rocm -I`:

[rocm-overlay.txt](https://github.com/justxi/rocm/files/5239048/rocm-overlay.txt)

From what I can see in the [corresponding source](https://github.com/yalue/rocm_mega_repo/blob/6834237381c08ba634d4dd9cff7c8051765fec96/sources/HIP/rocclr/hip_code_object.cpp#L92), `rocclr` fails to find some kind of a blob corresponding to `gfx906` device string and fails.

**Comment by justxi** [comment]
@heroxbd @littlewu2508 Do you have any idea?

**Comment by pshirshov** [comment]
I noticed that during `rocBLAS` build the command lines always include `GFX803` define, but not `GFX806`. Maybe something is wrong with the useflag?

**Comment by justxi** [comment]
Maybe... I will have a look on it.

**Comment by justxi** [comment]
@pshirshov Could you check and post the contents of "${WORKDIR}/target.lst"?

**Comment by pshirshov** [comment]
Seems like it's always wrong:

```
/var/tmp/portage/sci-libs/rocBLAS-3.7.0-r1/work # cat target.lst
gfx803
```

**Comment by heroxbd** [comment]
> Seems like it's always wrong:
> 
> ```
> /var/tmp/portage/sci-libs/rocBLAS-3.7.0-r1/work # cat target.lst
> gfx803
> ```

@littlewu2508 has faced with this problem with ROCm 3.7.  Maybe he has a solution.

**Comment by justxi** [comment]
> Seems like it's always wrong:
> 
> ```
> /var/tmp/portage/sci-libs/rocBLAS-3.7.0-r1/work # cat target.lst
> gfx803
> ```

Of course!
But why?
You have set only gfx906?

**Comment by pshirshov** [comment]
I've tried all the combinations, including just gfx906 -gfx803.

**Comment by justxi** [comment]
@littlewu2508 Could you share your hints or solution (if you have one)?

**Comment by littlewu2508** [comment]
> 
> 
> @littlewu2508 Could you share your hints or solution (if you have one)?

No, I can't even seen a target.lst in ${WORKDIR}. What @heroxbd described is an unrelated bug met in compiling pytorch with hip-3.7.0.

**Comment by justxi** [comment]
@littlewu2508 Strange... but it should be "target.lst"...

**Comment by perestoronin** [comment]
> tensorflow-rocm==2.3.0
From repository or ebuild you compiled tensorflow-rocm ?

**Comment by justxi** [comment]
Due to inactivity and that I will remove "target.lst", I close this. 
Please reopen if the discussion should be continued.
