### ISSUE TITLE
Please bump rocm to 3.8.0

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#170]
Please bump rocm to 3.8.0

**Comment by justxi** [comment]
Thanks for the hint. 
Before I start here, the ebuilds already in portage have to be updated.

**Comment by perestoronin** [comment]
Ok, this ebuilds exists only 3.7.0 version:

https://github.com/perestoronin/rocmnew/blob/master/dev-util/amd-rocm-meta/amd-rocm-meta-3.8.0.ebuild
```

		>=dev-libs/rocr-debug-agent-3.7.0
		>=dev-util/rocprofiler-3.7.0
		>=dev-util/roctracer-3.7.0
		>=sci-libs/rocFFT-3.7.0
```
