### ISSUE TITLE
miopen fails to build with boost 1.74.0-r1

### ISSUE THREAD

**Issue by pshirshov** [justxi/rocm#173]
I've upgraded my system to GCC 10 and rebuilt `@world`. The only package failed to build was `miopen`: [build.log](https://github.com/justxi/rocm/files/5397501/build.log)

Also I've tried `boost-static` use flag with no luck.

This is, possibly, an upstream issue.

Update: I've rechecked things, the failure is caused by boost version, I've downgraded it from `1.74.0-r1` back to `1.72` and `miopen` builds again.

**Comment by justxi** [comment]
I will check it for ROCm 3.9 and add a dependency for ROCm 3.8.

**Comment by justxi** [comment]
This still holds for ROCm 4.0.0.
I have added a dependency.
Thanks for reporting.
