### ISSUE TITLE
ROCm 4.0.0 ...

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#177]
I know that it is released... 
I will add ebuilds after the problems for 3.9/3.10 are fixed.

**Comment by justxi** [comment]
A first set of ebuilds for ROCm 4.0.0 is prepared and hopefully added to the official Gentoo portage soon... https://github.com/gentoo/gentoo/pull/18745

**Comment by justxi** [comment]
The ebuilds in official Gentoo portage are updated.
A few sci-libs ebuilds are also updated... 
Currently "rocBLAS" is the stopper.

**Comment by justxi** [comment]
The same issue with rocBLAS was already mentioned here -> https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/541

**Comment by perestoronin** [comment]
> The same issue with rocBLAS was already mentioned here -> [ROCmSoftwarePlatform/rocBLAS#541](https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/541)

rocmBLAS 4.0.0 compiled fine without any issue

https://github.com/perestoronin/rocmnew/blob/master/sci-libs/rocBLAS/rocBLAS-4.0.0.ebuild

**Comment by justxi** [comment]
Ok, the problem above was selfmade.
Hopefully rocBLAS compiles now.

**Comment by justxi** [comment]
All ebuilds are updated to ROCm 4.0.0.
