### ISSUE TITLE
sys-devel/hip-4.0 has dependency issue...

### ISSUE THREAD

**Issue by preney** [justxi/rocm#178]
When upgrading, hip 4.0 is skipped due to a missing dependency:

```
# emerge -pv sys-devel/hip

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sys-devel/hip-3.10.0:0/3.10::rocm  USE="profile -debug -hipify" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

!!! The following update has been skipped due to unsatisfied dependencies:

sys-devel/hip:0

  selected: (sys-devel/hip-3.10.0:0/3.10::rocm, ebuild scheduled for merge)
  skipped: (sys-devel/hip-4.0.0:0/4.0::rocm, ebuild scheduled for merge) (see unsatisfied dependency below)

emerge: there are no ebuilds to satisfy ">=dev-libs/rocclr-4.0".
(dependency required by "sys-devel/hip-4.0.0::rocm" [ebuild])
```

Should `>=dev-libs/rocclr-4.0` be `>=dev-libs/rccl-4.0` or is there a missing ebuild?

**Comment by justxi** [comment]
No, it seems you should update your Gentoo portage. It is in official Gentoo tree -> https://packages.gentoo.org/packages/dev-libs/rocclr

**Comment by preney** [comment]
I did sync portage before this. I just tried again and v3.10.0 is the highest version so presumably not all mirrors have picked it up yet.

**Comment by justxi** [comment]
That could be. 
You can ebuilds for ROCm 4.0.0 here -> https://github.com/gentoo/gentoo/tree/master/dev-libs/rocclr

**Comment by preney** [comment]
Thanks. I've pulled in an updated portage which has the newer ebuilds and things are emerging now. :-)

**Comment by justxi** [comment]
If you encounter any problems, feel free to report them here -> https://github.com/justxi/rocm/issues/177
