### ISSUE TITLE
opencl/clinfo not working because LLVM

### ISSUE THREAD

**Issue by stalkerg** [justxi/rocm#18]
GPU Vega56
For any interaction with OpenCL I have next error:
LLVM ERROR: Invalid abbrev number

After some googling, I found it's bound with LLVM. Also, I have no this error if I install ROCM from the git master (clinfo working fine and even some Blender cycles jobs). 
Strace not show anything good.

**Comment by justxi** [comment]
I updated my media-libs/ROCm-OpenCL-Runtime ebuild to 2.1, with roct-thunk-interface and rocr-runtime updated to version 2.1 with kernel gentoo-sources-4.20.6 clinfo reports expected values.

So I think the combination of llvm-roc and rocm-opencl-runtime needs improvements.

**Comment by stalkerg** [comment]
looks like with rocm 2.1 clinfo working fine, Thanks! You can close this issue.

**Comment by justxi** [comment]
ok
