### ISSUE TITLE
keras and rocm

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#181]
What about support rocm for keras ?

**Comment by justxi** [comment]
Does "keras" support for ROCm?

**Comment by justxi** [comment]
... but I think we should try to get tensorflow to work with ROCm =).

**Comment by justxi** [comment]
@perestoronin Here you can find some information about keras... https://github.com/justxi/rocm/issues/182

**Comment by justxi** [comment]
If you have a working ebuild feel free to create a PR to this or another repository.
