### ISSUE TITLE
rocBLAS-4.0.0 has empty Kernels.so-000-gfx*.hsaco

### ISSUE THREAD

**Issue by littlewu2508** [justxi/rocm#183]
On my way of building Pytorch-1.7.1 against rocm-4.0.0 on gentoo prefix, I encountered a stange bug : 

The Kernel Library of rocBLAS (${EPREFIX}/usr/lib64/rocblas/library/TensileLibrary_gfx906.co) keeps to be empty, both during and after installation. This is different from the official rocblas debian package, which contains non-empty files.

This is my installation image : 
```
ls -lh image/opt/gentoo/usr/lib64/rocblas/library                                                                                                                                        
total 344M
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx1010.hsaco
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx1011.hsaco
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx803.hsaco
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx900.hsaco
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx906.hsaco
-rw-r--r-- 1 wuyy wuyy    0 Jan 15 22:31 Kernels.so-000-gfx908.hsaco
-rw-r--r-- 1 wuyy wuyy  87M Jan 15 22:31 TensileLibrary.dat
-rw-r--r-- 1 wuyy wuyy 3.5M Jan 15 22:31 TensileLibrary_gfx803.co
-rw-r--r-- 1 wuyy wuyy  35M Jan 15 22:31 TensileLibrary_gfx900.co
-rw-r--r-- 1 wuyy wuyy  98M Jan 15 22:31 TensileLibrary_gfx906.co
-rw-r--r-- 1 wuyy wuyy 122M Jan 15 22:31 TensileLibrary_gfx908.co
```

Actually, these .hsaco and .co is empty before configure the source, and TensileLibrary is filled after calling TensileCreateLibrary during configuring. Does anyone know why the kernel libraries are not generated?

**Comment by justxi** [comment]
Currently not ...

**Comment by littlewu2508** [comment]
The source of this issue is found. In https://github.com/justxi/rocm/commit/29f88bc0b75b83190bad6900d9cf6949ffa4a2fd, I removed  `--genco` flag, which cause hipcc compiled Kernel.so cannot be offloaded to Kernels.so-000-gfx*.hsaco (which become empty files, since clang-offload-bundler generate empty file if no components exist in the bundle instead of just failing)

Such a removal of `--genco` flag is a hip issue, so we have to find our way out to let hipcc recognize `--genco`

**Comment by justxi** [comment]
ok

**Comment by heroxbd** [comment]
https://github.com/gentoo/sci/commit/5a6ca7469f59dd61a837ad34b60a9bb33b9f105b provides a fix for it.

**Comment by littlewu2508** [comment]
> 
> 
> [gentoo/sci@5a6ca74](https://github.com/gentoo/sci/commit/5a6ca7469f59dd61a837ad34b60a9bb33b9f105b) provides a fix for it.

Yes, that's the workaround I found.
