### ISSUE TITLE
Include an ebuild/use flag for hipfort as well

### ISSUE THREAD

**Issue by ketetefid** [justxi/rocm#185]
It would be great if the repository included an ebuild (or a flag) for building hipfort: Fortran Interface For GPU Kernel Libraries. 

hipfort is a very much desired tool for porting older, yet robust, routines which were written in Fortran, to GPU computing.

**Comment by justxi** [comment]
I pushed a first ebuild a few seconds ago: https://github.com/justxi/rocm/tree/master/dev-util/hipfort

I have to dependencies and check for correct installation according to FHS/Gentoo rules... but maybe it helps for the moment...
Let me know if it works or if you have any problems.

**Comment by ketetefid** [comment]
Thank you very much. I will test it as soon as I have got the time. For now, I will close this issue.
