### ISSUE TITLE
sys-kernel/rocm-sources:4.1.0 scripts don't have execute permission

### ISSUE THREAD

**Issue by preney** [justxi/rocm#186]
I tried building a kernel with sys-kernel/rocm-sources:4.1.0 which produced errors that there weren't permissions to run various .sh scripts. Investigating it looks like various .sh scripts don't have execute permissions set. After running:

```find . -name '*.sh' -exec chmod +x \{\} \;```

in /usr/src/linux-5.9.0-rc2_roc4.1.0/ I was able to successfully build the kernel. (The execute permissions appear to have been stripped from these scripts.) Was this intended or an error?

**Comment by justxi** [comment]
This is not intended. 
I used the same ebuild as for the previous versions.
I have to check why this happens.
Thanks for the hint.

**Comment by justxi** [comment]
Till now I didn´t find a solution. 
If someone has an idea, please reopen.
