### ISSUE TITLE
rocBLAS  from science overlay

### ISSUE THREAD

**Issue by perestoronin** [justxi/rocm#187]
https://bugs.gentoo.org/650804#c92

I tried compile self-bumped from science overlay ebuild, and it's failed:

ninja: error: '/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-rocm-4.1.0/library/src/blas3/Tensile/*.hpp', needed by 'include/internal/rocblas-exported-proto.hpp', missing and no known rule to make it

but execute /var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-rocm-4.1.0/library/src/blas3/Tensile/*.hpp

/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-rocm-4.1.0/library/src/blas3/Tensile/gemm_batched.hpp
/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-rocm-4.1.0/library/src/blas3/Tensile/gemm.hpp

Please fix rocBLAS

**Comment by xuhuisheng** [comment]
@perestoronin 
I meet this ninja bug, too. I am not sure Whether it is a ninja bug or cmake bug.

My workaround is:

1. cmake -G "Unix Makefiles" instead of -G "Ninja"
2. remove depends Tensile/*.hpp. https://github.com/xuhuisheng/rocm-build/blob/master/patch/22.rocblas-1.patch

**Comment by perestoronin** [comment]
Next error:
`Compiling source kernels: Launching 6 threads...
/opt/rocm/llvm/bin/clang-offload-bundler: error: Can't find bundles for hip-amdgcn-amd-amdhsa--gfx803
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/Tensile/Parallel.py", line 48, in apply_print_exception
    return func(*args)
  File "/usr/lib/python3.9/site-packages/Tensile/TensileCreateLibrary.py", line 207, in buildSourceCodeObjectFile
    subprocess.check_call(bundlerArgs)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/rocm/llvm/bin/clang-offload-bundler', '-type=o', '-targets=hip-amdgcn-amd-amdhsa--gfx803', '-inputs=/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-4.1.0_build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o', '-outputs=/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-4.1.0_build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.so-000-gfx803.hsaco', '-unbundle']' returned non-zero exit status 1.
multiprocessing.pool.RemoteTraceback: 
"""
`

**Comment by justxi** [comment]
Thanks for the information. 
I am currently waiting for acceptance of the my PR for the ebuilds in Gentoo portage, after that I will focus on all other ebuilds including rocBLAS.

**Comment by justxi** [comment]
Solved?

**Comment by littlewu2508** [comment]
> Next error:
> `Compiling source kernels: Launching 6 threads... /opt/rocm/llvm/bin/clang-offload-bundler: error: Can't find bundles for hip-amdgcn-amd-amdhsa--gfx803 Traceback (most recent call last): File "/usr/lib/python3.9/site-packages/Tensile/Parallel.py", line 48, in apply_print_exception return func(*args) File "/usr/lib/python3.9/site-packages/Tensile/TensileCreateLibrary.py", line 207, in buildSourceCodeObjectFile subprocess.check_call(bundlerArgs) File "/usr/lib/python3.9/subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['/opt/rocm/llvm/bin/clang-offload-bundler', '-type=o', '-targets=hip-amdgcn-amd-amdhsa--gfx803', '-inputs=/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-4.1.0_build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.o', '-outputs=/var/tmp/portage/sci-libs/rocBLAS-4.1.0/work/rocBLAS-4.1.0_build/library/src/build_tmp/TENSILE/code_object_tmp/Kernels.so-000-gfx803.hsaco', '-unbundle']' returned non-zero exit status 1. multiprocessing.pool.RemoteTraceback: """ `
> I passed -DTensile_ARCHITECTURE="gfx900", but rocBLAS tried compile kernel and for gfx803 ? Why ?

See [my understanding on TensileCreateLibrary](https://github.com/justxi/rocm/issues/194#issuecomment-898897989)

**Comment by littlewu2508** [comment]
> @perestoronin
> I meet this ninja bug, too. I am not sure Whether it is a ninja bug or cmake bug.
> Because makefile works fine.
> 
> My workaround is:
> 
>     * Use cmake -G "Unix Makefiles" instead of -G "Ninja"
> 
>     * Or remove depends Tensile/*.hpp with ninja. https://github.com/xuhuisheng/rocm-build/blob/master/patch/22.rocblas-1.patch

I back-ported a patch from upstream in rocBLAS-4.1::science which fixes the ninja build error

**Comment by perestoronin** [comment]
stack rocm upgraded to 4.3.0, and cmake generator fixed from ninja to emake:
```
EAPI=7

CMAKE_MAKEFILE_GENERATOR=emake
```
