### ISSUE TITLE
emerge: there are no ebuilds to satisfy "miopen" And "rocBLAS"

### ISSUE THREAD

**Issue by urgheuigrpauipeg** [justxi/rocm#188]
Everything is synced as far as I know, I am a new gentoo user so I may have overlooked something.

**Comment by justxi** [comment]
The ebuilds are in the science overlay.

**Comment by urgheuigrpauipeg** [comment]
> The ebuilds are in the science overlay.

I don't have 28Gib of ram, is there any way to get around that? Increasing the swap file did not help.

**Comment by justxi** [comment]
I had to upgrade my RAM.
But it depends what you want to compile, you could try to switch off all other architectures except the one you need.
Furthermore, check the projects own page, maybe they document more possibilities to reduce the needed RAM while compiling.

**Comment by justxi** [comment]
I think the original issue is solved. Feel free to open another if you still have problems.
