### ISSUE TITLE
ROCm 4.2: building llvm/clang - undefined reference to llvm::object::getELFSectionTypeName

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#190]
@candrews
@heroxbd
@littlewu2508 

Currently there is a problem with llvm-roc:

https://github.com/RadeonOpenCompute/ROCm/issues/1491

Maybe someone has an idea?

**Comment by littlewu2508** [comment]
Due to [driver issue on Radeon VII](https://rocmdocs.amd.com/en/latest/Current_Release_Notes/Current-Release-Notes.html)  my I haven't upgrade from 4.0 yet. I'll have a look on llvm-roc-4.2 next week.

**Comment by justxi** [comment]
Thanks. Would be very nice, because this blocks the update to all other ebuilds.

**Comment by littlewu2508** [comment]
I have reproduced the issue.

The direct cause is lib/Object/CMakeFiles/LLVMObject.dir/ELF.cpp.o and lib/Object/CMakeFiles/LLVMObject.dir/Error.cpp.o in  the build dir are not linked in. Further investigation is needed for fixing.
