### ISSUE TITLE
Clean up pathes in hip ebuild

### ISSUE THREAD

**Issue by littlewu2508** [justxi/rocm#192]
Seems that ROCm made a major change from 4.0 to 4.1. For hip, [AMD_PLATFORM changed from hcc to amd](https://github.com/RadeonOpenCompute/ROCm/blob/a44e82f26359a9dcf3f7706feaf893434546d9a6/README.md). These changes may cause patches and sed commands meaningless in >=hip-4.1 ebuilds, so I suppose we should perform a cleanup, which can make future version more maintainable.

**Comment by justxi** [comment]
ok, I will check it.

**Comment by justxi** [comment]
@littlewu2508 Here -> https://github.com/justxi/rocm/pull/193 we have a first set of ebuilds for ROCm 4.2 from @fuag15.
