### ISSUE TITLE
video group for portage

### ISSUE THREAD

**Issue by littlewu2508** [justxi/rocm#196]
I tried enabling sandbox and tested building packages. It seems that during src_configure, commands are executed as portage user, and portage does not belongs to video and render group, therefore it does not have permissions to /dev/kfd and /dev/dri/render*, causing troubles (although non-fatal: rocminfo and rocm_agent_enumerator fails to query device info) during build. I have to put portage into video and render group manually.

Since I'm mainly a prefix user and aren't experienced with sandbox and permissions, is there any existing workarounds that let portage access /dev/kfd without manually modifying group or permissions?

**Comment by justxi** [comment]
Interessting... I did not notice these problems. 
Are all ebuilds effected or only a few?

**Comment by littlewu2508** [comment]
> Interessting... I did not notice these problems.
> Are all ebuilds effected or only a few?

Currently I only noticed rocBLAS is affected, since TensileCreateLibrary uses rocm_agent_enumerator.

My current solution for rocBLAS-4.3 (will be PR to gentoo very soon) is to check permissions on /dev/kfd and so on at pkg_setup. If portage has no permissions, tell user to check permissions and exit.
