### ISSUE TITLE
Unable to emerge =dev-util/hip-4.3.0

### ISSUE THREAD

**Issue by preney** [justxi/rocm#197]
I have been unable to emerge hip since v4.1.0-r1 (v4.1.0 is what is installed). The errors are due to include file information, e.g., 

        In file included from /usr/include/vdi_common.hpp:26,
                         from /var/tmp/portage/dev-util/hip-4.3.0/work/HIP-rocm-4.3.0/rocclr/fixme.cpp:21:
        /usr/include/rocclr/platform/command.hpp: In constructor ‘amd::ClGlEvent::ClGlEvent(amd::Context&)’:
        /usr/include/rocclr/platform/command.hpp:344:41: error: ‘CL_COMMAND_GL_FENCE_SYNC_OBJECT_KHR’ was not         declared in this scope
          344 |   ClGlEvent(Context& context) : Command(CL_COMMAND_GL_FENCE_SYNC_OBJECT_KHR), context_(context) {
              |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        /usr/include/rocclr/platform/command.hpp:344:41: note: the macro ‘CL_COMMAND_GL_FENCE_SYNC_OBJECT_KHR’ had not yet been defined

yet rocclr v4.3.0 builds without issue (/usr/include/vdi_common.hpp comes from rocclr). Changing the version of the installed dev-util/opencl-headers doesn't change the error message and since dev-util/hip-4.3.0 is in the Gentoo repo now I presume it builds for others (hence this post). How can I get dev-util/hip to build? Which packages need to be installed / masked to achieve this? Thanks.

**Comment by justxi** [comment]
Due to the fact, that it build fine on my system I don´t have a solution yet.
And you are right, the ebuild is in portage now... Please open a bug at https://bugs.gentoo.org

**Comment by preney** [comment]
Someone else has: https://bugs.gentoo.org/790164 --not just 4.1.0 but 4.3.0 is also mentioned there.

**Comment by justxi** [comment]
ok.

**Comment by preney** [comment]
Concerning this issue I have posted my v4.3.0 fix as [Comment 13](https://bugs.gentoo.org/790164#c13) to the aforementioned bug https://bugs.gentoo.org/790164 . (It appears that the issue is identical for v4.3.0 and v4.1.0 and likely v4.2.0.)
