### ISSUE TITLE
Improvements for the rocm-opencl-runtime ebuild

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#20]
Some things to improve:
 - llvm-roc is hard coded, maybe this could be changed
 - there are libraries included, maybe it is possible to create own ebuilds

**Comment by justxi** [comment]
ROCm 2.1 is out, I will the installation with this version also.

**Comment by bluescarni** [comment]
The ``rocm-opencl-runtime`` ebuild fails for me. It builds most of it, I believe, but then errors out when trying to build the tests?

```
[ 97%] Built target oclc_isa_version_810.amdgcn.inc_target
[ 97%] Built target oclc_isa_version_802_lib
[ 97%] Built target oclc_isa_version_802.amdgcn.inc_target
[100%] Built target oclrocm
[  0%] Built target opencl_driver
[  0%] Built target roc-cl
[  0%] Performing download step (git clone) for 'googletest'
CMake Error at googletest-stamp/googletest-download-Release.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-P' '/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/build/compiler/driver/src/unittest/googletest-prefix/tmp/googletest-gitclone.cmake'

  See also

    /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/build/compiler/driver/src/unittest/googletest-prefix/src/googletest-stamp/googletest-download-*.log

make[2]: *** [compiler/driver/src/unittest/CMakeFiles/googletest.dir/build.make:90: compiler/driver/src/unittest/googletest-prefix/src/googletest-stamp/googletest-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:318: compiler/driver/src/unittest/CMakeFiles/googletest.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
 * ERROR: dev-libs/rocm-opencl-runtime-2.1.0::rocm failed (compile phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 124:  Called src_compile
 *   environment, line 2853:  Called die
 * The specific snippet of code:
 *       make -j1 || die
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/rocm-opencl-runtime-2.1.0::rocm'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/rocm-opencl-runtime-2.1.0::rocm'`.
 * The complete build log is located at '/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/build'
 * S: '/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/ROCm-OpenCL-Runtime-roc-2.1.0'
```

The error log says:

```
Cloning into 'googletest'...
fatal: unable to access 'https://github.com/google/googletest/': Could not resolve host: github.com
Cloning into 'googletest'...
fatal: unable to access 'https://github.com/google/googletest/': Could not resolve host: github.com
Cloning into 'googletest'...
fatal: unable to access 'https://github.com/google/googletest/': Could not resolve host: github.com
CMake Error at /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/build/compiler/driver/src/unittest/googletest-prefix/tmp/googletest-gitclone.cmake:75 (message):
  Failed to checkout tag: 'master'
```

The ``.out`` log says:

```
-- Had to git clone more than once:
          3 times.
```

I have no idea why it would not be able to resolve github.com, as I don't seem to have any network connection issues. But if I restart the ebuild, it always fails at the same point.

**Comment by davidrohr** [comment]
@bluescarni : The problem is that the rocm cmake will try to fetch additional files during the compile phase. Gentoo disables network access during the compile phase for security reasons.
I think this should at some point be fixed in the e-build. We could either just use a system installation of google-test (which is the package they are fetching during the build), or just disable the tests.
Anyhow, as a workaround you can use the env variable FEATURES=-network-sandbox in order to make it compile.

**Comment by bluescarni** [comment]
@davidrohr thanks a lot for the information, indeed ``FEATURES=-network-sandbox`` fixes the build.

I am also experiencing the segfault mentioned by @justxi. I tried to compile a few examples from Boost.Compute which used to work with the opencl-runtime I had installed before (1.9.9999 from August, I believe), and now they are segfaulting as well. So this would seem to be a real regression.

**Comment by ernsteiswuerfel** [comment]
I guess the ebuild should depend on app-admin/chrpath. Without it installed I get:
```
[...]
-- Installing: /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image/usr/lib/x86_64/libamdocl64.so
-- Set runtime path of "/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image//usr/lib/x86_64/libamdocl64.so" to ""
-- Installing: /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image/usr/bin/clinfo
-- Set runtime path of "/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image//usr/bin/clinfo" to ""
/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/environment: line 2886: chrpath: command not found
/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/environment: line 2899: chrpath: command not found
>>> Completed installing rocm-opencl-runtime-2.1.0 into /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image/

 * Final size of build directory: 357288 KiB (348.9 MiB)
 * Final size of installed tree:  162636 KiB (158.8 MiB)

 * QA Notice: command not found:
 * 
 * 	/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/environment: line 2886: chrpath: command not found
 * 	/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/temp/environment: line 2899: chrpath: command not found
Auto fixing rpaths for /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image/usr/lib64/OpenCL/vendors/roc/libOpenCLDriverStub.so

 * QA Notice: The following files contain insecure RUNPATHs
 *  Please file a bug about this at https://bugs.gentoo.org/
 *  with the maintainer of the package.
 *   /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/image/usr/lib64/OpenCL/vendors/roc/libOpenCLDriverStub.so
 *     RPATH: /usr/lib/llvm/roc-2.1.0/lib:/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.1.0/work/build/lib
 * 

Files matching a file type that is not allowed:
   usr/lib/libamdocl64.so
 * ERROR: dev-libs/rocm-opencl-runtime-2.1.0::rocm failed:
 *   multilib-strict check failed!
```

**Comment by justxi** [comment]
I added the dependency "app-admin/chrpath".

**Comment by ernsteiswuerfel** [comment]
Thanks, now the ebuild properly pulls it in if not installed.

**Comment by justxi** [comment]
@bluescarni @davidrohr: I could "solve" the problem with the googletest, the rocm-opencl-driver has a unittest which loads the additional software. I remove this in e.g. media-libs/ROCm-OpenCL-Runtime.

**Comment by davidrohr** [comment]
That is good news. It the rocm-opencl-runtime working now, or do we still need to use the ROCm-OpenCL-Runtime?

**Comment by justxi** [comment]
@davidrohr For me it is not working. It segfaults. I currently try to find the difference while building libamdocl64.so. I uploaded my current version of dev-libs/rocm-opencl-runtime recently.

**Comment by stalkerg** [comment]
I don't know why but dev-libs/rocm-opencl-runtime-2.2.0 try to use my system clang instead of AMD one.

**Comment by justxi** [comment]
Yes, there is a path missing. I hope I get this fixed in the coming days.

**Comment by justxi** [comment]
I decided to stop splitting the ebuild for rocm-opencl-runtime. Instead of this, I created "dev-libs/rocm-opencl-runtime" based on "media-libs/ROCm-OpenCL-Runtime" with the enhancement, that it uses "git-r3" eclass to checkout sources.

**Comment by davidrohr** [comment]
@justxi : I do not find this new dev-libs/rocm-opencl-runtime in your current repo

**Comment by justxi** [comment]
Sorry, I forgot to upload it. Now it should be accessible.

**Comment by ernsteiswuerfel** [comment]
Current dev-libs/rocm-opencl-runtime-2.3.0 ebuild does not correctly pull in some deps:
```
virtual/blas
dev-libsroct-thunk-interface-2.3.0
dev-libsrocr-runtime-2.3.0
```

**Comment by justxi** [comment]
Thanks, I added the dependencies, except "roct-thunk-interface" because it is pulled in by "rocr-runtime".

**Comment by justxi** [comment]
Due to the fact that it seems there are currently no problems, I close this issue.
