### ISSUE TITLE
hcc not finding a shared object

### ISSUE THREAD

**Issue by bluescarni** [justxi/rocm#22]
I just updated hcc from 1.9 to 2.1 using the latest ebuilds. Now if I try to run an executable compiled with ``hcc``'s ``-hc`` mode, it will not run because it is unable to find a library:

```
C++AMP runtime load error: libmcwamp_cpu.so: cannot open shared object file: No such file or directory
Can't load CPU runtime!
```

The mentioned library is in ``/usr/lib64/hcc/2.1/lib/``, and if I put this directory in ``LD_LIBRARY_PATH`` then the executable runs fine. Not sure if this is an hcc issue or if this is specific to the gentoo ebuild.

**Comment by davidrohr** [comment]
Should be fixed by justxi/rocm#23

**Comment by justxi** [comment]
Merged.

**Comment by justxi** [comment]
If there are still any problems, please reopen.

**Comment by bluescarni** [comment]
Yep, just re-merged hcc a moment ago an it is working fine now. Thanks!
