### ISSUE TITLE
hip-2.0.0.ebuild and hip-2.1.0.ebuild both with SLOT="2.1"

### ISSUE THREAD

**Issue by ernsteiswuerfel** [justxi/rocm#28]
Could it be https://github.com/justxi/rocm/blob/master/sys-devel/hip/hip-2.0.0.ebuild erroneously pulls in 2.1 deps? Noticed this as an upgrade wants to downgrade hcc + hip from 2.1.0 to 2.0.0.

**Comment by justxi** [comment]
I changed the slots. But I think due to the fact, that all use the same env files currently only one of the package can be installed.
