### ISSUE TITLE
rocPRIM

### ISSUE THREAD

**Issue by bluescarni** [justxi/rocm#3]
Would it be possible to have an ebuild for rocPRIM as well?

https://github.com/ROCmSoftwarePlatform/rocPRIM

Thanks for the great work!

**Comment by justxi** [comment]
Yes, this one of the next ebuilds I want to create.

**Comment by bluescarni** [comment]
Awesome, thanks!

**Comment by justxi** [comment]
You can find a first ebuild for rocPRIM, but this installs the headers only and not in the Gentoo desired way. I have to correct the links to the header and cmake files. But maybe it helps in a first stage. 

While compiling the tests I got an error, in the meantime I disabled building of the tests with a patch.

**Comment by bluescarni** [comment]
Thanks! It installed successfully, but I haven't had the chance to actually test it yet. I'll give it a spin in the weekend and report how it goes.

**Comment by justxi** [comment]
Now rocprim is installed in /usr/lib. Please test it.

**Comment by justxi** [comment]
Hmm, you could create a link in /usr/include  ... ln -s ../lib64/hcc/1.9/include hcc 
I will check the ebuild for hcc.

**Comment by justxi** [comment]
Could you provide your example?

**Comment by justxi** [comment]
Due to the fact that an experimental ebuild exist and a solution for the project exist. 
So I close this issue.
