### ISSUE TITLE
Digest verification and wrong verison

### ISSUE THREAD

**Issue by Davidescion** [justxi/rocm#32]
[usr@gen3] ~ $ sudo emerge --ask dev-libs/rocm-opencl-runtime

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U ~] dev-libs/rocm-opencl-runtime-2.2.0 [2.1.0]

Would you like to merge these packages? [Yes/No] y

>>> Verifying ebuild manifests

!!! Digest verification failed:
!!! /var/lib/layman/rocm/dev-libs/rocm-opencl-runtime/files/rocm-opencl-runtime-2.2.0-add-paths.patch
!!! Reason: Failed on BLAKE2B verification
!!! Got: 6927b5cb85bb6108539418d92f4dad2c2642de3baf2a8a5dd2f539b580769fdb24a59fb1fa8b6d80a2e0257d8a9e20484bc11027a62006b014a8e93e0dacd9ad
!!! Expected: d8c62da9d1b01e5d62d8fd82f50af53dcee687a035a7f4f3a3e89410992405679962dc011fab8c17626952ef79c505c8eaea04f53649a6ad721384bdd326cbc7

**Comment by justxi** [comment]
I will correct this as soon as possible.

**Comment by justxi** [comment]
I merged a PR by davidrohr, please test again.
