### ISSUE TITLE
Compilation failing rocm-opencl-runtime 2.2.0

### ISSUE THREAD

**Issue by Davidescion** [justxi/rocm#33]
[build.log](https://github.com/justxi/rocm/files/2989753/build.log)

**Comment by justxi** [comment]
I know this, I currently trying to resolve this.
Think, the path to /usr/lib64/llvm/roc-2.2.0/lib is missing in the command line.

**Comment by perkinslr** [comment]
The `ld` command is missing `-L/usr/lib/llvm/roc-2.2.0/lib` 
I don't know enough about cmake to know the proper way to fix it.  I just replaced /usr/x86_64-pc-linux-gnu/binutils-bin/2.30/ld with a wrapper that added the missing library search path during the build.

**Comment by justxi** [comment]
Interestingly this path is part of command parameters when the compiler is invoked.

**Comment by justxi** [comment]
This problem is also mentioned here https://github.com/justxi/rocm/issues/20
