### ISSUE TITLE
manifest failure preventing installation of any dev-libs/rocm-opencl-runtime

### ISSUE THREAD

**Issue by ZeroChaos-** [justxi/rocm#37]
* Digest verification failed:
 * /var/db/repos/rocm/dev-libs/rocm-opencl-runtime/rocm-opencl-runtime-2.2.0.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 4624
 * Expected: 4834

**Comment by justxi** [comment]
Should be fixed now.
