### ISSUE TITLE
Digest verification failed, filesize does not match, file is not listed in manifest

### ISSUE THREAD

**Issue by kabeero** [justxi/rocm#39]
Hi, I'm trying to use your overlay for ROCm-2.5.0

`$ sudo layman -o https://raw.githubusercontent.com/justxi/rocm/master/repositories.xml -f -a rocm`

then

```
$ sudo emerge -avq hcc
 * Digest verification failed:
 * /var/lib/layman/rocm/sys-devel/hcc/hcc-9999-r2.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 810
 * Expected: 816
 * Digest verification failed:
 * /var/lib/layman/rocm/sys-devel/hcc/hcc-9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 686
 * Expected: 692
 * Digest verification failed:
 * /var/lib/layman/rocm/sys-devel/hcc/hcc-2.0.9999.ebuild
 * Reason: Filesize does not match recorded size
 * Got: 787
 * Expected: 793
 ...
```

```
$ sudo emerge -avq =sys-devel/amd-rocm-meta-2.5.0
 * A file is not listed in the Manifest: '/var/lib/layman/rocm/sys-devel/hip/hip-2.0.0.ebuild'

!!! All ebuilds that could satisfy "=sys-devel/hip-2.5.0*" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-devel/hip-2.5.0::rocm (masked by: corruption)

(dependency required by "sys-devel/amd-rocm-meta-2.5.0::rocm" [ebuild])
(dependency required by "=sys-devel/amd-rocm-meta-2.5.0" [argument])
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

I see other issues like this that were patched. Am I doing something wrong or is this a recurring bug?

Thanks!

**Comment by justxi** [comment]
Hi, I updated the manifest files.
Please try again.

**Comment by kabeero** [comment]
Thanks for the update. I should have included more info, there are still some outstanding Manifest differences:

> $ sudo emerge -vq dev-libs/rocm-opencl-runtime
> >>> Verifying ebuild manifests
> 
> !!! Digest verification failed:
> !!! /var/lib/layman/rocm/dev-libs/rocr-runtime/rocr-runtime-2.1.0.ebuild
> !!! Reason: Filesize does not match recorded size
> !!! Got: 900
> !!! Expected: 862

or for meta package:

> $ sudo emerge -vq amd-rocm-meta
> >>> Verifying ebuild manifests
> 
> !!! Digest verification failed:
> !!! /var/lib/layman/rocm/dev-libs/rocr-runtime/rocr-runtime-2.1.0.ebuild
> !!! Reason: Filesize does not match recorded size
> !!! Got: 900
> !!! Expected: 862
> 
> !!! A file listed in the Manifest could not be found: /var/lib/layman/rocm/dev-util/rocm-smi/rocm-smi-2.0.9999.ebuild
> 
> !!! Digest verification failed:
> !!! /var/lib/layman/rocm/sys-devel/hcc/hcc-2.1.0.ebuild
> !!! Reason: Filesize does not match recorded size
> !!! Got: 2370
> !!! Expected: 2369
> 
> !!! A file listed in the Manifest could not be found: /var/lib/layman/rocm/sys-devel/hip/files/1.9.9999-DisableTest.patch

**Comment by justxi** [comment]
I have also updated and uploaded the file.

**Comment by kabeero** [comment]
emerge rocm-opencl-runtime is now working!

but amd-rocm-meta reports a new issue:

> $ sudo emerge -vq amd-rocm-meta
> >>> Verifying ebuild manifests
> 
> !!! Digest verification failed:
> !!! /var/lib/layman/rocm/sys-devel/hcc/hcc-2.2.0.ebuild
> !!! Reason: Filesize does not match recorded size
> !!! Got: 855
> !!! Expected: 854

this did not show up in my previous emerge log... I think sys-devel/hcc/Manifest needs patches enclosed

[hcc-manifest-patch.txt](https://github.com/justxi/rocm/files/3272966/hcc-manifest-patch.txt)

after these patches, some checksums/file size for media-libs/hsa-amd-aqlprofile-1.0.0 did not match either so Manifest patch for this is also enclosed

[hsa-amd-aqlprofile-patch.txt](https://github.com/justxi/rocm/files/3272967/hsa-amd-aqlprofile-patch.txt)

during installation, I ran into another compilation problem during cmake of rocminfo-9999:

> CMake Error at CMakeLists.txt:23 (message):
>   Can't find libhsa-runtime64.so.

this does indeed exist:

> $ ls /usr/lib64/libhsa-runtime64.so
> /usr/lib64/libhsa-runtime64.so

so I may need to tweak cmake script...

thank you for your help! sorry to bug you

**Comment by justxi** [comment]
I updated the manifests. 
"rocminfo" install and works.

**Comment by kabeero** [comment]
rocminfo-1.0.0 has this error:

```
$ sudo emerge -vq amd-rocm-meta
>>> Verifying ebuild manifests
>>> Emerging (1 of 4) dev-util/rocminfo-1.0.0::rocm
>>> Failed to emerge dev-util/rocminfo-1.0.0, Log file:
>>>  '/var/tmp/portage/dev-util/rocminfo-1.0.0/temp/build.log'
>>> Jobs: 0 of 4 complete, 1 failed            Load avg: 0.53, 1.08, 1.34
 * Package:    dev-util/rocminfo-1.0.0
 * Repository: rocm
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * Applying rocminfo-python2.patch ...
 [ ok ]
 * Hardcoded definition(s) removed in CMakeLists.txt:
 *  set(CMAKE_BUILD_TYPE ${BUILD_TYPE})
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-util/rocminfo-1.0.0/work/rocminfo-1.0.0_build"
cmake -C /var/tmp/portage/dev-util/rocminfo-1.0.0/work/rocminfo-1.0.0_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DROCM_DIR=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-util/rocminfo-1.0.0/work/rocminfo-1.0.0_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-util/rocminfo-1.0.0/work/rocminfo-1.0.0
loading initial cache file /var/tmp/portage/dev-util/rocminfo-1.0.0/work/rocminfo-1.0.0_build/gentoo_common_config.cmake
ERROR: Define ROCR_LIB_DIR pointing to ROCR libraries is not set
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE
```

rocminfo-9999 has this error:

```
$ sudo emerge -vq amd-rocm-meta
>>> Verifying ebuild manifests
>>> Emerging (1 of 4) dev-util/rocminfo-9999::rocm
>>> Failed to emerge dev-util/rocminfo-9999, Log file:
>>>  '/var/tmp/portage/dev-util/rocminfo-9999/temp/build.log'
>>> Jobs: 0 of 4 complete, 1 failed            Load avg: 0.69, 1.02, 1.30
 * Package:    dev-util/rocminfo-9999
 * Repository: rocm
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * Repository id: RadeonOpenCompute_rocminfo.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_RADEONOPENCOMPUTE_ROCMINFO
 *   EGIT_OVERRIDE_BRANCH_RADEONOPENCOMPUTE_ROCMINFO
 *   EGIT_OVERRIDE_COMMIT_RADEONOPENCOMPUTE_ROCMINFO
 *   EGIT_OVERRIDE_COMMIT_DATE_RADEONOPENCOMPUTE_ROCMINFO
 * 
 * Fetching https://github.com/RadeonOpenCompute/rocminfo ...
git fetch https://github.com/RadeonOpenCompute/rocminfo +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/dev-util/rocminfo/0/__main__ refs/git-r3/HEAD
 * Repository id: RadeonOpenCompute_rocm-cmake.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_RADEONOPENCOMPUTE_ROCM_CMAKE
 *   EGIT_OVERRIDE_BRANCH_RADEONOPENCOMPUTE_ROCM_CMAKE
 *   EGIT_OVERRIDE_COMMIT_RADEONOPENCOMPUTE_ROCM_CMAKE
 *   EGIT_OVERRIDE_COMMIT_DATE_RADEONOPENCOMPUTE_ROCM_CMAKE
 * 
 * Fetching https://github.com/RadeonOpenCompute/rocm-cmake/ ...
git fetch https://github.com/RadeonOpenCompute/rocm-cmake/ +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/dev-util/rocminfo/0/__main__ refs/git-r3/HEAD
 * Checking out https://github.com/RadeonOpenCompute/rocminfo to /var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/RadeonOpenCompute/rocminfo
   at the commit:            4e30bc4a5b3b9ef6efbe6571a8b7f799201a210c
 * Checking out https://github.com/RadeonOpenCompute/rocm-cmake/ to /var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999/rocm-cmake ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               https://github.com/RadeonOpenCompute/rocm-cmake/
   at the commit:            68fb6b3373bcecadd937d7ab0a1c3adaf6a1b13e
 * Hardcoded definition(s) removed in CMakeLists.txt:
 *  set(CMAKE_INSTALL_PREFIX "/opt/rocm" CACHE PATH "")
 * Hardcoded definition(s) removed in rocm-cmake/CMakeLists.txt:
 *  set(CMAKE_INSTALL_PREFIX "/opt/rocm" CACHE PATH "")
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999_build"
cmake -C /var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999
loading initial cache file /var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:23 (message):
  Can't find libhsa-runtime64.so.
```

**Comment by justxi** [comment]
Hmm, you could download "rocminfo" manually, with git and run the compilation manually too, to check if this related to the ebuild.

**Comment by kabeero** [comment]
> download "rocminfo" manually, with git and run the compilation manually

github://rocminfo does build successfully after emerging rocm-cmake from your overlay

from the previous error messages, I tried installing rocm-device-libs and re-emerged rocminfo but same issues existed

can you post what rocm packages you have installed for a successful rocminfo compilation?

```
$ eix -cI rocm
[I] dev-libs/rocm-cmake [1] (9999@06/10/2019): ROCm-CMake
[I] dev-libs/rocm-device-libs [1] (2.2.0(0/2.2)@06/10/2019): ROCm-Device-Libs
[I] dev-libs/rocm-opencl-runtime [1] (2.5.0@06/10/2019): ROCm-OpenCL-Runtime
[U] dev-util/rocm-smi [1] (2.5.0@06/10/2019 -> (~)9999): ROCm System Management Interface
[1] "rocm" /var/lib/layman/rocm
```

**Comment by justxi** [comment]
Thanks, I added the dependency to rocminfo.

A list of working packages is in: https://github.com/justxi/rocm/blob/master/README.md
ROCm-Device-Libs is not needed for e.g. the use of OpenCL (it is used internally)

**Comment by justxi** [comment]
Which version of rocminfo do you use, 1.0.0 or 9999?
I use 9999.
But due to the fact that it checks out the latest version, it could be neccessary that I have to add something.

**Comment by kabeero** [comment]
I was using rocminfo-9999 from overlay, and latest from github

I think I've found the reason for rocminfo-9999 build failing,

from the github://rocminfo repo, when I built manually with cmake then make, it created cmake config that used this ROCR_LIB_DIR:
`build/CMakeCache.txt:ROCR_LIB_DIR:PATH=/usr/lib64`

but when the build fails and I check 
`/var/tmp/portage/dev-util/rocminfo-9999/work/rocminfo-9999_build/CMakeCache.txt:ROCR_LIB_DIR:PATH=ROCR_LIB_DIR-NOTFOUND`

is there a way to edit the .ebuild to change ROCR_LIB_DIR to point to /usr/lib64?

**Comment by justxi** [comment]
Look at the ebuild of version 1.0.0, there you find "mycmakeargs" in "src_configure", there you can add more paramters.

**Comment by kabeero** [comment]
Thanks!

I have attached patches for Manifest and ebuild, now `$ emerge rocminfo hcc` works fine
[rocminfo-9999-ebuild-patch.txt](https://github.com/justxi/rocm/files/3277968/rocminfo-9999-ebuild-patch.txt)
[rocminfo-Manifest-patch.txt](https://github.com/justxi/rocm/files/3277969/rocminfo-Manifest-patch.txt)


but `$ emerge rocm-opencl-driver` needed Manifest patch
[rocm-opencl-driver-Manifest.txt](https://github.com/justxi/rocm/files/3277963/rocm-opencl-driver-Manifest.txt)

**Comment by justxi** [comment]
I removed the interal dependency for cmake files from rocminfo. Can you please try the latest version, if it is working for you also?

The rocm-opencl-driver manifest is updated. 
Thanks for the hints.

**Comment by kabeero** [comment]
Looks good, `rocminfo` and `rocm-opencl-driver` rebuilt with no problems

Thanks for your help and overlay

**Comment by hagar-dunor** [comment]
Hi

I have this issue trying to build sys-devel/amd-rocm-meta-2.5.0:

tail /var/tmp/portage/media-libs/hsa-amd-aqlprofile-1.0.0/temp/build.log

!!! Fetched file: hsa-amd-aqlprofile_1.0.0_amd64.deb VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      56080
!!! Expected: 56082

Cheers

**Comment by justxi** [comment]
I updated it a few days ago, but I will check it again.

**Comment by justxi** [comment]
I updated the manifest again.
