### ISSUE TITLE
Another manifest mismatch: hsa-amd-aqlprofile

### ISSUE THREAD

**Issue by Hackerpilot** [justxi/rocm#41]
Looks like the file was modified on 07-Jun-2019 20:12. They're clearly not following semantic versioning.

http://repo.radeon.com/rocm/apt/debian/pool/main/h/hsa-amd-aqlprofile/

**Comment by justxi** [comment]
Thanks for the information, I will fix it in the evening.

**Comment by justxi** [comment]
Should be fixed now.
