### ISSUE TITLE
Getting rocm working with tensorflow-rocm python pip package

### ISSUE THREAD

**Issue by devang** [justxi/rocm#46]
Like the title says, trying to get the tensorflow-rocm python pip package working currently gives an error about rocRAND missing. I don't see an ebuild for it, could you add it or maybe I could work on a pull request.

**Comment by devang** [comment]
pip tensorflow-rocm still requires ebuilds for https://github.com/RadeonOpenCompute/clang-ocl and https://github.com/ROCmSoftwarePlatform/MIOpen and whatever else MIOpen needs

ImportError: libMIOpen.so.1: cannot open shared object file: No such file or directory

I'm using all the 2.5 ebuilds

**Comment by justxi** [comment]
I merged your ebuilds. 
I currently have limited time, but feel free to add more ebuilds. 
If you need someone who tests your ebuild or need help, post here in the forum.

**Comment by justxi** [comment]
Any progress?
Can you provide version 2.6 for your contributed ROCm ebuilds?

**Comment by devang** [comment]
I haven't had time to work on this, I will try to update as I can. 

If anyone else wants to pick this up with ebuilds of https://github.com/ROCmSoftwarePlatform/MIOpen (and it's dependencies) please feel free and post here.

**Comment by justxi** [comment]
I close this due to inactivity.
Please reopen, if someone wants to contribute.

**Comment by devang** [comment]
Added working MIOpen, MIOpenGEMM, half ebuilds, and an experimental rccl ebuild. Could you test install these? @justxi The rccl ebuild currently fails for me with "x86_64-pc-linux-gnu-g++: error: unrecognized command line option ‘-h’". Not sure where to start troubleshooting..

**Comment by devang** [comment]
Could you reopen this and tag this as a bug/feature?

**Comment by justxi** [comment]
I think you did not set CXX="..." to hcc?
See "Manual build" in https://github.com/ROCmSoftwarePlatform/rccl

**Comment by devang** [comment]
Thanks, I thought cmake would take care of which compiler to use once it found hip/hcc in the configure step, but I guess not. 

rocminfo, and rocm-smi work for me, and doing this in python doesn't show missing libs anymore: 
echo -e "import tensorflow as tf\nprint(\"tf devices: \", tf.config.experimental.get_visible_devices())"|python

It also doesn't show available devices, yet.

**Comment by devang** [comment]
Adding this udev rule works: https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md#using-debian-based-rocm-with-upstream-kernel-drivers

echo 'SUBSYSTEM=="kfd", KERNEL=="kfd", TAG+="uaccess", GROUP="video"' | sudo tee /etc/udev/rules.d/70-kfd.rules

Closing issue as all ebuilds are done.

**Comment by justxi** [comment]
Not related to the topic, but... 
You marked the ebuilds that they fulfill FHS, I tested "rccl" and the ebuild complains about iinstalling to an unexspected path. I changed that for rccl (-> 2.7.0-r1). If you have time, you could check it for MIOpen and MIOpenGEMM and create a patch too?
