### ISSUE TITLE
Clean up old packages

### ISSUE THREAD

**Issue by davidrohr** [justxi/rocm#52]
The reposity has the full history containing also the 1.x packages. Should we clean this up at some point, and keep only the last 2 or 3 releases?

**Comment by justxi** [comment]
Yes, good idea for the future. 
I think currently I would try to add some more packages to ROCM 2.6.
If ROCM 2.7 is completely rolled out, we should focus on that, especially on building HIP against system llvm.

**Comment by justxi** [comment]
In addition unbundling of rocm-opencl-runtime should be fixed, then we have all ebuilds in a good state. I think this would be a good point to clean up this repository, then we can also remove ebuilds which are already in Gentoo portage.

**Comment by justxi** [comment]
@candrews will update the ebuilds which are already in portage to version 2.7. 
So we should remove all ebuilds which are already in Portage and update the dependencies of the remaining packages.

**Comment by justxi** [comment]
I will test the new 2.7 ebuilds in portage on my second system and then I clean up the ebuilds.

**Comment by justxi** [comment]
I cleaned up all packages, which are already in portage.

**Comment by justxi** [comment]
I think we can remove all ebuilds except the ones for ROCm 2.6 and 2.7 or what do you think?
Some 9999 ebuilds could also be kept, if they are up-to-date.

**Comment by davidrohr** [comment]
I agree I'd remove everything but 2.6, 2.7 and 9999. I'd actually keep the 9999, and we should adjust the ebuilds such that it is the same physical file for 2.7 and 9999, only steered by the ${PV} variable.
btw rocminfo and rocm-smi still have wrong install paths to /opt/rocm.

**Comment by candrews** [comment]
I agree - that's how I've done the ebuilds in Gentoo.
I also only have -9999 ebuilds for packages that work without patching... Which isn't a lot of ROC packages, unfortunately.

**Comment by justxi** [comment]
@davidrohr rocminfo is an old one, this can be removed. rocm-smi must be updated.

**Comment by justxi** [comment]
So I removed all old ebuilds. 
I also removed all old 9999 ebuilds, but not all remaining 9999 ebuilds are up-to-date.
I updated rocminfo and rocm-smi.
