### ISSUE TITLE
Streamline installation directories

### ISSUE THREAD

**Issue by davidrohr** [justxi/rocm#53]
I think the install directories are currently a bit inconsistent.
- Some stuff still goes to /opt/rocm
- llvm-roc / hip / hcc goes to their own directories, like the clang compiler, which is probably OK.
- Some go to /usr/[package_name]
- Some go directly to /usr
This seems a bit weird to me, also picking up the packages via CMake is annoying, basically for everything that is not directly in /usr, we have to set ROOTPATH or CMAKE_..._PREFIX in an env file. I think this is OK for llvm-roc / hip / cub, but doesn't make much sense for all the sci-libs.
Should we perhaps just install them to /opt/rocm, or move everything to /usr/rocm. Then we'd basically need only one ROOTPATH for CMake to pick everything up.

**Comment by justxi** [comment]
Your are right. My first focus was on getting things to work.
As long as the CMake configurations are installed correctly it should not matter, 
but I think we should comply with the FHS or Gentoo if it differs.
Doing this, would mean to move the executables from /opt/rocm to /usr/bin.
llvm-roc / hip / hcc are ok. The libraries could go to /usr.

Before we start that, we should keep track of what AMD is doing. 

And much more important, we should discuss it with @candrews, because he is working also on this and we should try to comply with the Gentoo rules to omit double work.

**Comment by davidrohr** [comment]
One problem I see with installing to /usr:
We certainly don't want to pollute /usr/include directly with all the sci-libs stuff for instalce, so the headers (eg for rocThrust) must go either to /usr/include/rocThrust or to /usr/rocm/rocThrust/include or to /usr/rocThrust/include.
I absolutely do not like /usr/rocThrust directly, because we will pollute /usr significantly.

Therefore, I thought perhaps for all that utility stuff, to coalesce it somewhere unter /usr/rocm (instead of /opt/rocm).
As additional advantage, if we put everything to /usr/rocm/[PACKAGE], we can (hopefully) take more or less the normal ROCM builds with their cmake. If we want to change it to /usr/include/rocThrust, I think we need to mess with plenty of CMake files to make the ROCM packages find their headers.

But I agree, we should discuss this with @candrews, come to a conclusion, and then clean this up.

**Comment by candrews** [comment]
We should be installing everything according to FHS/Gentoo standards. So don't use /opt or /usr/rocm, for example, as those aren't FHS locations.

A key thing we all should be doing is performing the fixes as patches to the CMake files (so not overriding the CMake installation in `src_install` and doing it all manually, for example), and submitting those changes as PRs upstream. Our goal is to get everything fixed upstream so we don't have to keep making and updating hacks for each new release.

As to whether they want to install to to /usr/lib64/roc or just /usr/lib64... I think we have to make a best effort and submit PRs, then see what AMD says. Ultimately it's up to them to make that decision, and as long as they're consistent (so, for example, we won't need to mess with plenty of CMake files to make the ROCM packages find their headers), it'll all work out.

**Comment by justxi** [comment]
Sorry, I don´t mean "/usr" for the libraries.

**Comment by justxi** [comment]
I added a column "FHS" to the README page, to keep track of this.

@candrews Can I assume, that all ebuilds which are in portage now, comply to the FHS/Gentoo standards?

**Comment by candrews** [comment]
> Can I assume, that all ebuilds which are in portage now, comply to the FHS/Gentoo standards?

Yes, as far as I know / can tell :-)

**Comment by justxi** [comment]
I updated the list and I think it looks better than expected.
@davidrohr @candrews I think the ebuilds marked with "(ok)" install to standard locations.

Only dev-util/rocprofiler and dev-util/rocm-smi must be changed.

**Comment by davidrohr** [comment]
Hm, ok, if you say so. I had the feeling some packages have weird installation directories. But I'll double check once all 2.7 packages are there (for now, I reverted to my 2.6 RPM installation).
In particular, the sci-libs packages.

One more point for the readme: I have added hipCUB for 2.7 in my PR, and I am not sure if we need both rocThrust and hipThrust: The headers in both git repos are almost identical, and hipThrust wasn't touched for some months already. Also the ROM only has rocThrust. So perhaps, we don't need hipThrust after all.

For systems known to work, you may add Intel Core i7 6700K / Radeon VII / PCIe 3.0 over Thunderbolt 3

**Comment by justxi** [comment]
I didn´t check the sci-libs packages, there I think is something todo. 

Ok, I can remove hipThrust or we keep it in the list, because it is listed here "https://github.com/RadeonOpenCompute/ROCm" and if someone needs it we can care about it.

**Comment by justxi** [comment]
According to https://github.com/RadeonOpenCompute/ROCm hipThrust will be removed in the future.

**Comment by justxi** [comment]
I updated the ebuilds for rocm-smi and rocprofiler to install to standard locations.
That means only the science libraries are left. I will try to change the path while updating them to version 2.6.

**Comment by davidrohr** [comment]
@justxi : I already added science libraries to 2.7 in my PR. Perhaps we can adapt them directly to avoid extra work.

**Comment by justxi** [comment]
@davidrohr Yes, I have seen it =).

**Comment by justxi** [comment]
I suggest to install the headers for the sci-libs to "/usr/include/rocBLAS" (needs to be adjusted) or "/usr/include/rocPRIM". So we do not flood the "/usr/include".

**Comment by davidrohr** [comment]
This sounds reasonable to me.

**Comment by justxi** [comment]
Ok, I changed the install path for rocBLAS. 
So we have for all ebuilds which exist for ROCm 2.6, except one, corrected to install the standard paths.

**Comment by justxi** [comment]
The ROCm libraries are partially versioned with e.g. 2.6 or 2.6.0. I suggest to use for the build 2.6.0 in general and use "ver_cut 1-2" where necessary.

Furthermore there are only three ebuilds left, then all ebuilds install to standard locations.

**Comment by justxi** [comment]
Ok, all ebuilds of ROCm 2.6 in this repository install now to standard locations.
Therefore I close this issue.
