### ISSUE TITLE
ROCm GCC OpenMP/OpenACC Offloading

### ISSUE THREAD

**Issue by sjnewbury** [justxi/rocm#6]
I've had support for buildinig gcc offload accelerators in my gentoo-gpu overlay for a long time based on a modified toolchain.eclass and offload-gcc-* ebuilds.  It had been bit-rotting for a while since I have no supported hardware.  Just last week I had a support request which pointed out it wasn't building, so I had an incentive to get it working again and clean things up a bit.  NVPTX target should be working now.

I read on Phoronix recently that AMD have provided patches to support ROCm as an offload accelerator so I need to look into getting it supported.  Did you want to help get it working, and perhaps include it in this overlay?  I can't test it unfortunately, unless the latest ROCm code supports using HSA_ENABLE_SDMA=0 with POLARIS10 since my CPU is an FX-9370.

**Comment by justxi** [comment]
Yes, I am interessted. 
Where can I find the code?

Do you have ebuilds for the nvptx stuff?
I tried it in a manual build a few month ago.

**Comment by sjnewbury** [comment]
https://github.com/sjnewbury/gentoo-gpu

sys-devel/gcc-offload-nvptx are basically just a regular gcc ebuilds, the magic is in the modified toolchain.eclass.  It should be easy enough to add whatever dependencies are needed for ROCm to the eclass and prepare the toolchain in the same way.  At the moment it is only known to build successfully for NVPTX, I hoped to get it working with the discrete GPU in my laptop when I originally worked on a couple of years ago, but unfortunately Fermi is too old.

Obviously I never had an Intel MIC, who does?  But I did consider it in the eclass.

**Comment by sjnewbury** [comment]
That's a lot cheaper than new!! ;-)
https://www.ebay.co.uk/itm/Intel-Xeon-Phi-71S1P-61-cores-1-1GHz-8GB-RAM/163316162223?epid=3024830053&hash=item260666deaf:g:cj4AAOSwjZlbxDls:rk:2:pf:0

**Comment by justxi** [comment]
You mean these patches?

https://gcc.gnu.org/ml/gcc-patches/2018-09/msg00264.html

**Comment by sjnewbury** [comment]
Yeah, it's only gone in recently so will need to be applied through an ebuild or use a live git ebuild.

**Comment by justxi** [comment]
I found also this https://www.phoronix.com/scan.php?page=news_item&px=AMD-GCN-GPU-2018-Cauldron.  They hope to add it for the final release of GCC 9. I will check if it s already part of the gcc repository, otherwise I have to extract the patches from the mailinglist.

**Comment by justxi** [comment]
Do you know a tool to extract the patches automatically from the mailing list?

**Comment by sjnewbury** [comment]
Fortunately the GCC mailing list archive has a raw email export mode:

https://gcc.gnu.org/ml/gcc-patches/2018-09/msg00265.html
You'll see a link 

`Other format: | [Raw text]`

Which will lead you to

https://gcc.gnu.org/cgi-bin/get-raw-msg?listname=gcc-patches&date=2018-09&msgid=c6dd9ca09af7c41d10feed487994c768694eef50.1536144068.git.ams%40codesourcery.com

You can then use the raw emails as patch input.

**Comment by sjnewbury** [comment]
patch ignores the extra email headers/body text.  git can actually automatically create a commit directly from a properly formatted raw email.

**Comment by sjnewbury** [comment]
I suggest using wget "<raw url> and -O <filename>

**Comment by justxi** [comment]
I have currently limited time to work on this.
But it seems that adding the patches is in progress:
https://gcc.gnu.org/git/?p=gcc.git;a=search;h=HEAD;s=ams;st=author

**Comment by sjnewbury** [comment]
@justxi I was a bit over optimistic about the progress they had made.  Looks like the initial support isn't too interesting with just code gen supported, with offload support coming in later.  I read on Phoronix that the initial code drop is only single threaded, which might be why offloading isn't available yet...!

**Comment by justxi** [comment]
Yes, as I read it is only the C frontend, for code gen other assembler tools are necessary.
I will close this for now - we can reopen it when there is more progress.
