### ISSUE TITLE
Compiler and dependencies for HIP

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#61]
@davidrohr We have different ebuilds for llvm-roc in my repo and in Gentoo portage. Which do you use to build HIP? When the ones in Gentoo portage are ok, then I will remove the other from my repo.

**Comment by davidrohr** [comment]
I use llvm-roc from gentoo.
As written in #56 , hip 2.7 does not work with hip-clang (at least for me), hip 9999 works.

**Comment by justxi** [comment]
But using hip 2.7 without the USE flag hip-clang works?

**Comment by davidrohr** [comment]
If you build hip 2.7 without use flags, it will use hcc as hip compiler backend.
There is the useflag `clang`, which will enable the hipify tool: This is an independent tool that uses the system clang (sys-devel/clang >= 8) to convert CUDA files to HIP, it has nothing to do with hip-clang.

If you set the other `llvm-roc-backend` use flag, hip will use llvm-roc (clang) as compiler instead of hcc.
If I do this, building hip works both with hip 2.7 and with hip 9999.
But at least for me, compiling hip files fails in the 2.7 case, (i.e. hip 2.7 with llvm-roc-backend use flag). HIP 2.7 with hcc works.
hip 9999 works with either hcc or llvm-roc.

**Comment by justxi** [comment]
I build "hip" with "+clang debug +hcc-backend llvm-roc-backend", so it should work.

**Comment by justxi** [comment]
And maybe we can build with llvm-roc with ROC 2.8.

**Comment by davidrohr** [comment]
I think 2.7 is as good as it gets. For hip-clang and for opencl, I'd wait for 2.8. I think at least most ebuilds are in a reasonable state now. Hopefully, 2.8 doesn't change too much so we can use them directly.

**Comment by justxi** [comment]
Which version of llvm-roc do you use?
2.7 or have you created a 9999 ebuild?

This could be also interessting:
https://github.com/illuhad/hipSYCL/issues/106

**Comment by davidrohr** [comment]
I use llvm-roc 2.7 from gentoo

**Comment by justxi** [comment]
@davidrohr I think we should rename the USE flag "clang" for "HIP" to "hipify", because as you described it results in building "hipify".

**Comment by davidrohr** [comment]
@justxi : Fine with me, I just called it clang since it depends on the system clang, so if people have a global clang use flag set, they will build it. But I have no strong opinion actually.

**Comment by justxi** [comment]
Yes of course, but here it could be confused with hcc/hip-clang toolchains.

**Comment by justxi** [comment]
@davidrohr 
> hip 9999 works with either hcc or llvm-roc.

If llvm-roc is used hcc is not necessary?
Then I could make the dependency depend on the hcc USE flag.

**Comment by davidrohr** [comment]
No! Hcc is also needed when llvm-roc is used for compilation.
According to the documentation in the hip github repo, amd will remove the hcc dependency some time in the future.
Kind Regards
David Rohr

**Comment by justxi** [comment]
Ok, interesstingly setting "HIP_PLATFORM=hip-clang" compiles also.
Build with the now commented lines:
https://github.com/justxi/rocm/blob/master/sys-devel/hip/hip-2.7.9999.ebuild

**Comment by justxi** [comment]
So now I can compile the "vectoradd" HIP example.
But I had to set ROCM_PATH="/usr", otherwise "rocm_agent_enumerator" is not found.

**Comment by davidrohr** [comment]
I had the same issue. The problem appeared when we changed the install paths of rocminfo and rocm-smi. Perhaps one of them should create an env.d file that sets ROCM_PATH?
Kind Regards
David Rohr

**Comment by justxi** [comment]
I think there is currently no progress on this... I close this.
