### ISSUE TITLE
rocBLAS - INTERFACE_INCLUDE_DIRECTORIES property contains path

### ISSUE THREAD

**Issue by justxi** [justxi/rocm#63]
The following must be fixed before the "rocBLAS" ebuild can use "cmake-utils":

CMake Error in library/src/CMakeLists.txt:
  Target "rocblas" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-rocm-2.7/library/src/"

  which is prefixed in the source directory.

**Comment by justxi** [comment]
Til now I could not reproduce it and did not find the line we it must happen in the CMakeLists.txt file.

**Comment by justxi** [comment]
I will test the "master-rocm-2.8" branch... (using the identical named branch for rocALUTION solved some problems there too)

**Comment by Lucretia** [comment]
Can you push this branch?

**Comment by justxi** [comment]
I currently test my 2.8 version of the rocBLAS ebuild... It take a minute to compile...

**Comment by Lucretia** [comment]
I mean the full 2.8.x branch you have for all packages. I can try to build that too.

**Comment by justxi** [comment]
I currently have no full 2.8 branch because only the libraries from AMD (hier in sci-libs/*) have master-rocm-2.8 branches.

**Comment by justxi** [comment]
Interesstingly this... 

```  
set( Tensile_INC
    ${CMAKE_CURRENT_SOURCE_DIR}/blas3/Tensile
    ${CMAKE_BINARY_DIR}/Tensile
 )
```

[...]

```
target_include_directories( rocblas
  PUBLIC  $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/library/include>
          $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
          $<BUILD_INTERFACE:${PROJECT_BINARY_DIR}/include>
          $<BUILD_INTERFACE:${Tensile_INC}>
          $<INSTALL_INTERFACE:include>
          )
```
becomes this:
```
$<BUILD_INTERFACE:/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-rocm-2.7/library/include>
$<BUILD_INTERFACE:/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-rocm-2.7/library/src/include>
$<BUILD_INTERFACE:/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-2.7.0_build/include>
/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-rocm-2.7/library/src/
$<BUILD_INTERFACE:/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-rocm-2.7/library/src/blas3/Tensile/var/tmp/portage/sci-libs/rocBLAS-2.7.0-r1/work/rocBLAS-2.7.0_build/Tensile>
$<INSTALL_INTERFACE:include>
```

**Comment by justxi** [comment]
The above result is interesting, but does not need to be solved.
This problem was created by a patch which is not needed any more.
