### ISSUE TITLE
Wrong CMake targets in sci-libs after installing to /usr

### ISSUE THREAD

**Issue by davidrohr** [justxi/rocm#64]
The CMake config files for the sci-libs packages are wrong since we have moved the headers to /usr/include. E.g., hipCUB'sa hipcub-config.cmake exports /usr/hipcub/include instead of /usr/include/hipcub. I think it is the same problem for all of them, since beforehand the includes were in /opt/rocm/hipcub/include, etc.

**Comment by davidrohr** [comment]
Also some of the cmake recipres are in /usr/lib/cmake, others in /usr/lib64/cmake. I think they should all go to /usr/lib64

**Comment by justxi** [comment]
Ok, I checked all others except hipCUB and hipThrust. They are ok. I check hipCUB and hipThrust as soon as possible.

**Comment by davidrohr** [comment]
I think at least rocPRIM was also wrong

**Comment by justxi** [comment]
This is my file list for rocPRIM-2.7.0:

 * Searching for rocPRIM ...
 * Contents of sci-libs/rocPRIM-2.7.0:
/usr
/usr/include
/usr/include/rocprim
/usr/include/rocprim/block
/usr/include/rocprim/block/block_discontinuity.hpp
/usr/include/rocprim/block/block_exchange.hpp
/usr/include/rocprim/block/block_histogram.hpp
/usr/include/rocprim/block/block_load.hpp
/usr/include/rocprim/block/block_load_func.hpp
/usr/include/rocprim/block/block_radix_sort.hpp
/usr/include/rocprim/block/block_reduce.hpp
/usr/include/rocprim/block/block_scan.hpp
/usr/include/rocprim/block/block_sort.hpp
/usr/include/rocprim/block/block_store.hpp
/usr/include/rocprim/block/block_store_func.hpp
/usr/include/rocprim/block/detail
/usr/include/rocprim/block/detail/block_histogram_atomic.hpp
/usr/include/rocprim/block/detail/block_histogram_sort.hpp
/usr/include/rocprim/block/detail/block_reduce_raking_reduce.hpp
/usr/include/rocprim/block/detail/block_reduce_warp_reduce.hpp
/usr/include/rocprim/block/detail/block_scan_reduce_then_scan.hpp
/usr/include/rocprim/block/detail/block_scan_warp_scan.hpp
/usr/include/rocprim/block/detail/block_sort_bitonic.hpp
/usr/include/rocprim/config.hpp
/usr/include/rocprim/detail
/usr/include/rocprim/detail/all_true.hpp
/usr/include/rocprim/detail/binary_op_wrappers.hpp
/usr/include/rocprim/detail/match_result_type.hpp
/usr/include/rocprim/detail/radix_sort.hpp
/usr/include/rocprim/detail/various.hpp
/usr/include/rocprim/device
/usr/include/rocprim/device/config_types.hpp
/usr/include/rocprim/device/detail
/usr/include/rocprim/device/detail/device_binary_search.hpp
/usr/include/rocprim/device/detail/device_histogram.hpp
/usr/include/rocprim/device/detail/device_merge.hpp
/usr/include/rocprim/device/detail/device_merge_sort.hpp
/usr/include/rocprim/device/detail/device_partition.hpp
/usr/include/rocprim/device/detail/device_radix_sort.hpp
/usr/include/rocprim/device/detail/device_reduce.hpp
/usr/include/rocprim/device/detail/device_reduce_by_key.hpp
/usr/include/rocprim/device/detail/device_scan_lookback.hpp
/usr/include/rocprim/device/detail/device_scan_reduce_then_scan.hpp
/usr/include/rocprim/device/detail/device_segmented_radix_sort.hpp
/usr/include/rocprim/device/detail/device_segmented_reduce.hpp
/usr/include/rocprim/device/detail/device_segmented_scan.hpp
/usr/include/rocprim/device/detail/device_transform.hpp
/usr/include/rocprim/device/detail/lookback_scan_state.hpp
/usr/include/rocprim/device/detail/ordered_block_id.hpp
/usr/include/rocprim/device/detail/uint_fast_div.hpp
/usr/include/rocprim/device/device_binary_search.hpp
/usr/include/rocprim/device/device_histogram.hpp
/usr/include/rocprim/device/device_histogram_config.hpp
/usr/include/rocprim/device/device_merge.hpp
/usr/include/rocprim/device/device_merge_config.hpp
/usr/include/rocprim/device/device_merge_sort.hpp
/usr/include/rocprim/device/device_merge_sort_config.hpp
/usr/include/rocprim/device/device_partition.hpp
/usr/include/rocprim/device/device_radix_sort.hpp
/usr/include/rocprim/device/device_radix_sort_config.hpp
/usr/include/rocprim/device/device_reduce.hpp
/usr/include/rocprim/device/device_reduce_by_key.hpp
/usr/include/rocprim/device/device_reduce_by_key_config.hpp
/usr/include/rocprim/device/device_reduce_config.hpp
/usr/include/rocprim/device/device_run_length_encode.hpp
/usr/include/rocprim/device/device_run_length_encode_config.hpp
/usr/include/rocprim/device/device_scan.hpp
/usr/include/rocprim/device/device_scan_by_key.hpp
/usr/include/rocprim/device/device_scan_config.hpp
/usr/include/rocprim/device/device_segmented_radix_sort.hpp
/usr/include/rocprim/device/device_segmented_radix_sort_config.hpp
/usr/include/rocprim/device/device_segmented_reduce.hpp
/usr/include/rocprim/device/device_segmented_scan.hpp
/usr/include/rocprim/device/device_select.hpp
/usr/include/rocprim/device/device_select_config.hpp
/usr/include/rocprim/device/device_transform.hpp
/usr/include/rocprim/device/device_transform_config.hpp
/usr/include/rocprim/functional.hpp
/usr/include/rocprim/intrinsics
/usr/include/rocprim/intrinsics.hpp
/usr/include/rocprim/intrinsics/atomic.hpp
/usr/include/rocprim/intrinsics/bit.hpp
/usr/include/rocprim/intrinsics/thread.hpp
/usr/include/rocprim/intrinsics/warp.hpp
/usr/include/rocprim/intrinsics/warp_shuffle.hpp
/usr/include/rocprim/iterator
/usr/include/rocprim/iterator.hpp
/usr/include/rocprim/iterator/arg_index_iterator.hpp
/usr/include/rocprim/iterator/constant_iterator.hpp
/usr/include/rocprim/iterator/counting_iterator.hpp
/usr/include/rocprim/iterator/detail
/usr/include/rocprim/iterator/detail/replace_first_iterator.hpp
/usr/include/rocprim/iterator/discard_iterator.hpp
/usr/include/rocprim/iterator/texture_cache_iterator.hpp
/usr/include/rocprim/iterator/transform_iterator.hpp
/usr/include/rocprim/iterator/zip_iterator.hpp
/usr/include/rocprim/rocprim.hpp
/usr/include/rocprim/rocprim_version.hpp
/usr/include/rocprim/type_traits.hpp
/usr/include/rocprim/types
/usr/include/rocprim/types.hpp
/usr/include/rocprim/types/double_buffer.hpp
/usr/include/rocprim/types/integer_sequence.hpp
/usr/include/rocprim/types/key_value_pair.hpp
/usr/include/rocprim/types/tuple.hpp
/usr/include/rocprim/warp
/usr/include/rocprim/warp/detail
/usr/include/rocprim/warp/detail/warp_reduce_crosslane.hpp
/usr/include/rocprim/warp/detail/warp_reduce_dpp.hpp
/usr/include/rocprim/warp/detail/warp_reduce_shared_mem.hpp
/usr/include/rocprim/warp/detail/warp_reduce_shuffle.hpp
/usr/include/rocprim/warp/detail/warp_scan_crosslane.hpp
/usr/include/rocprim/warp/detail/warp_scan_dpp.hpp
/usr/include/rocprim/warp/detail/warp_scan_shared_mem.hpp
/usr/include/rocprim/warp/detail/warp_scan_shuffle.hpp
/usr/include/rocprim/warp/detail/warp_segment_bounds.hpp
/usr/include/rocprim/warp/detail/warp_sort_shuffle.hpp
/usr/include/rocprim/warp/warp_reduce.hpp
/usr/include/rocprim/warp/warp_scan.hpp
/usr/include/rocprim/warp/warp_sort.hpp
/usr/lib64
/usr/lib64/cmake
/usr/lib64/cmake/rocprim
/usr/lib64/cmake/rocprim/rocprim-config-version.cmake
/usr/lib64/cmake/rocprim/rocprim-config.cmake
/usr/lib64/cmake/rocprim/rocprim-targets.cmake
/usr/share
/usr/share/doc
/usr/share/doc/rocPRIM-2.7.0
/usr/share/doc/rocPRIM-2.7.0/README.md.bz2

**Comment by davidrohr** [comment]
The files are installed correctly, but cmake gets the wrong path from find_package(hipcub). We'll have to patch the cmake files that are installed.
Kind Regards
David Rohr

**Comment by justxi** [comment]
Ok.

**Comment by justxi** [comment]
Instead of patching the installed cmake files, it should be possible to change the appropriate cmake commands which generate them.

**Comment by davidrohr** [comment]
Sure, but I am afraid these commands are also in a CMake file.
Kind Regards
David Rohr

**Comment by justxi** [comment]
Ok, as a workaround you could could patch them =)

**Comment by justxi** [comment]
I changed the INSTALL_INTERACE for hipCUB, can you please verify if this fixes the problem?
Then I would change all other ebuilds.

**Comment by justxi** [comment]
hipCUB, rocThrust and rocPRIM should be ok now.

**Comment by justxi** [comment]
Due to the fact, that the initial problem is fixed, I close this issue.

**Comment by davidrohr** [comment]
@justxi : I was offline for few days. I can confirm that your fix works. Thx.

**Comment by justxi** [comment]
Does linking work also?

**Comment by davidrohr** [comment]
Just tried hipCUB, which is header only
