### ISSUE TITLE
Remove hsa-ext-rocr from this overlay

### ISSUE THREAD

**Issue by candrews** [justxi/rocm#65]
@mkszuba added [dev-libs/hsa-ext-rocr/hsa-ext-rocr](https://github.com/gentoo/gentoo/tree/master/dev-libs/hsa-ext-rocr) to Gentoo, so please remove the package from this overlay to eliminate any confusion.

Thanks!

**Comment by justxi** [comment]
Ok, deleted.

But why does the ebuild from @mkszuba not download the deb file itself?

**Comment by mkszuba** [comment]
I couldn't find any terms and conditions for using packages from repo.radeon.com (nor the exact licence under which hsa-ext-rocr-dev libraries are distributed, for that matter) so I have decided to play it safe at first and possibly adjust it later. Do you know more about this, perhaps? If not I guess I'll have to either open an issue in one of ask some of the AMD devs contributing to those projects.

**Comment by justxi** [comment]
Ok, that makes it clear. And no, I didn´t find any terms of conditions, on the ROCm github page there are only install hints for Debian, Ubuntu and CentOS/RHEL.
