### ISSUE TITLE
repo init fails for rocm-opencl-runtime

### ISSUE THREAD

**Issue by rexy712** [justxi/rocm#7]
I'm trying to emerge ROCm-OpenCL-Runtime-1.9.9999 and I keep getting an error when it's running the `repo init -u https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.git -b roc-1.9.x -m opencl.xml` command:
```
>>> Unpacking source...
gpg: keybox '/var/tmp/notmpfs/portage/media-libs/ROCm-OpenCL-Runtime-1.9.9999/homedir/.repoconfig/
gnupg/pubring.kbx' created
gpg: /var/tmp/notmpfs/portage/media-libs/ROCm-OpenCL-Runtime-1.9.9999/homedir/.repoconfig/gnupg/tr
ustdb.gpg: trustdb created
gpg: key 16530D5E920F5C65: public key "Repo Maintainer <repo@android.kernel.org>" imported
gpg: can't connect to the agent: IPC connect call failed
gpg: key 67B7E448692B382C: public key "Conley Owens <cco3@android.com>" imported
gpg: can't connect to the agent: IPC connect call failed
gpg: Total number processed: 2
gpg:               imported: 2
fatal: registering repo maintainer keys failed
error: command 'sync' requires repo to be installed first.
         Use "repo init" to install it here.
```

When I run the same command as my user or as the root user manually it works fine.

**Comment by justxi** [comment]
Hi,

I will try to test it tomorrow.

**Comment by justxi** [comment]
I haved tested the ebuild, but I can not reproduce the problem. 
Have you tried again? 
Maybe a temporary problem?

**Comment by rexy712** [comment]
No it's still occurring. I was wondering if it had something to do with the portage user on my system. I manually init the repo as portage using `su portage -s /bin/bash -c "repo init -u https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime.git -b roc-1.9.x -m opencl.xml"` and that works fine as long as i have permissions on the directory.

**Comment by justxi** [comment]
Any progress on this issue?

**Comment by rexy712** [comment]
No it's still happening. I haven't been able to find any similar issues anywhere. I probably have something set up incorrectly, I have no idea what to check though.
What I ended up doing was running the emerge then pausing it before the error and running the command manually then resuming the emerge. Everything worked after that.

I'll close the issue since it seems isolated to my system.
