### ISSUE TITLE
hipcc wants rocm_agent_enumerator in /opt but it's not there

### ISSUE THREAD

**Issue by Lucretia** [justxi/rocm#73]
```
$ hipcc -h
Can't exec "/opt/rocm/bin/rocm_agent_enumerator": No such file or directory at /usr/lib/hip/bin/hipcc line 690.
Use of uninitialized value $myAgents in split at /usr/lib/hip/bin/hipcc line 691.
Died at /usr/lib/hip/bin/hipcc line 733.
No valid AMD GPU target was either specified or found. Please specify a valid target using --amdgpu-target=

$ rocm_agent_enumerator 
gfx000
gfx701

$ which rocm_agent_enumerator 
/usr/bin/rocm_agent_enumerator
```

**Comment by Lucretia** [comment]
```ROCM_PATH=/usr/ hipcc --help```

works. This this needs to be in /etc/env.d/ somewhere.

**Comment by justxi** [comment]
Set ROCM_PATH="/usr/"...

**Comment by Lucretia** [comment]
what I'm saying is, this variable really should be installed in part of the env.d scripts so you don't have to set it by hand.

**Comment by justxi** [comment]
Yes, I forgot to care about this. I thinking about, which package should create an entry to env.

**Comment by Lucretia** [comment]
hip

**Comment by justxi** [comment]
@davidrohr What do you think?

**Comment by davidrohr** [comment]
Yes, I mentioned this in one of my earlier PRs already.
I don't think it should belong to HIP, but rather one of the base packages.
- rocm-runtime?
- or juist rocminfo / rocm-smi, which bring the executables?
- Or we just patch hip to get rid of the env variable. Perhaps there is no reason to have yet another variable only for this single case?
Would all be ok for me.

**Comment by Lucretia** [comment]
>     * Or we just patch hip to get rid of the env variable. Perhaps there is no reason to have yet another variable only for this single case?

This is the best case.

**Comment by justxi** [comment]
I agree, if it is only used in hip then we should patch it.

**Comment by justxi** [comment]
The ebuild hip-2.7.0-r1 includes a patch for hipcc. 
Please test and report.

**Comment by justxi** [comment]
Please reopen if there are still any problems.
