### ISSUE TITLE
rocBLAS and miopen ebuilds not working

### ISSUE THREAD

**Issue by devang** [justxi/rocm#76]
When I try to emerge miopen-2.6.0 I get this: 
```
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Imported target "roc::rocblas" includes non-existent path

    "PORTAGE_TMPDIR/portage/sci-libs/rocBLAS-2.6/work/rocBLAS-rocm-2.6/library/src/"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```
When I try to emerge miopen-2.7.0, I get a compilation failure from not finding the rocBLAS headers, until I turn rocBLAS off (which it is currently). Can we change rocBLAS for this? 

Not sure what is going on with rocBLAS and miopen 2.6, but the rocBLAS ebuild seems to be setting some paths wrong.

**Comment by justxi** [comment]
You can try to add this line to the 2.6 ebuild:
https://github.com/justxi/rocm/blob/875902fc2e8c41c8482302ca24207b8968285e2b/sci-libs/rocBLAS/rocBLAS-2.7.0-r1.ebuild#L61

**Comment by justxi** [comment]
> When I try to emerge miopen-2.7.0, I get a compilation failure from not finding the rocBLAS headers, until I turn rocBLAS off (which it is currently). Can we change rocBLAS for this?

The ebuild rocBLAS-2.7.0-r1 should export the include path correctly.

**Comment by devang** [comment]
Ok, doing those two changes worked for 2.6, and using r1 for 2.7 also worked. Thanks.
