### ISSUE TITLE
Could NOT find ROCT (missing: FIND_ROCT_INCLUDES)

### ISSUE THREAD

**Issue by nethershaw** [justxi/rocm#79]
With rocm-opencl-runtime-2.6.0-r1 and rocm-opencl-runtime-2.7.0, I encounter this CMake error in src_configure():

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ROCT (missing: FIND_ROCT_INCLUDES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindROCT.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)
```

In version 2.5.0 of the ebuild, I was able to merge successfully. I will attach my emerge --info and the build log for 2.7.0 here. I imagine you may need more information to help troubleshoot, but just ask and I will be happy to provide.

Attachments:
[build.log](https://github.com/justxi/rocm/files/3581573/build.log)
[emerge-info.txt](https://github.com/justxi/rocm/files/3581575/emerge-info.txt)

**Comment by justxi** [comment]
Interessting... Besides this for rocm-opencl-runtime-2.6.0-r1 you could file a bug report at bugs.gentoo.org, because the ebuild is in official Gentoo portage. 

Can you provide: 
> equery files dev-libs/roct-thunk-interface?

The missing header files should be in /usr/include

**Comment by nethershaw** [comment]
Ah, yes. I see the problem.

The files installed by dev-libs/roct-thunk-interface are here:

```
equery files dev-libs/roct-thunk-interface
 * Searching for roct-thunk-interface in dev-libs ...
 * Contents of dev-libs/roct-thunk-interface-2.7.0:
/usr
/usr/include
/usr/include/libhsakmt
/usr/include/libhsakmt/hsakmt.h
/usr/include/libhsakmt/hsakmttypes.h
/usr/lib64
/usr/lib64/cmake
/usr/lib64/cmake/hsakmt
/usr/lib64/cmake/hsakmt/hsakmt-config-version.cmake
/usr/lib64/cmake/hsakmt/hsakmt-config.cmake
/usr/lib64/libhsakmt.so -> libhsakmt.so.1
/usr/lib64/libhsakmt.so.1 -> libhsakmt.so.1.0.6
/usr/lib64/libhsakmt.so.1.0.6
/usr/lib64/pkgconfig
/usr/lib64/pkgconfig/libhsakmt.pc
/usr/share
/usr/share/doc
/usr/share/doc/roct-thunk-interface-2.7.0
/usr/share/doc/roct-thunk-interface-2.7.0/README.md.bz2
```
But CMake is looking for them elsewhere:
```
grep -R FIND_ROCT_INCLUDES /tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/
/tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/rocm-opencl-runtime-2.7.0_build/CMakeCache.txt:FIND_ROCT_INCLUDES:PATH=FIND_ROCT_INCLUDES-NOTFOUND
/tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/ROCm-OpenCL-Runtime-roc-2.7.0/cmake/modules/FindROCT.cmake:find_path(FIND_ROCT_INCLUDES hsakmt.h HINTS /opt/rocm/include)
/tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/ROCm-OpenCL-Runtime-roc-2.7.0/cmake/modules/FindROCT.cmake:                                  FIND_ROCT_INCLUDES FIND_ROCT_LIBRARIES)
/tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/ROCm-OpenCL-Runtime-roc-2.7.0/cmake/modules/FindROCT.cmake:mark_as_advanced(FIND_ROCT_INCLUDES FIND_ROCT_LIBRARIES)
/tmp/portage/dev-libs/rocm-opencl-runtime-2.7.0/work/ROCm-OpenCL-Runtime-roc-2.7.0/cmake/modules/FindROCT.cmake:set(ROCT_INCLUDES ${FIND_ROCT_INCLUDES})
```
I refer to the second result. Indeed, copying the hsakmt headers and libraries from the roct-thunk-interface package into /opt/rocm/include and /opt/rocm/lib respectively allows the package to configure and build successfully.

In fact I found the solution in [a patch from a fork of your repository](https://github.com/davidrohr/rocm/blob/df4504b69ac647ab8e69bda11dcb6ba0d775a6c8/dev-libs/rocm-opencl-runtime/files/roct-include-path.patch). If I remove my temporary /opt/rocm location and place that patch in /etc/portage/patches/dev-libs/rocm-opencl-runtime-2.7.0/roct-include-path.patch, then CMake successfully finds those headers and libraries in their installed locations.

**Comment by nethershaw** [comment]
This appears to be a regression. The patch I cited in my previous comment is from one of your contributors and was merged here in df4504b69ac647ab8e69bda11dcb6ba0d775a6c8, but then the patch was removed with the cleanup of version 2.6 ebuilds in c023e54c8d7ced69a6ae1086f46017bd8b297a48.

**Comment by justxi** [comment]
Interesting ... my header files are in "/usr/include" not in "/usr/include/libhsakmt".
Which version of "dev-libs/roct-thunk-interface-2.7.0" are you using, the one from Gentoo portage?

**Comment by nethershaw** [comment]
The one from this overlay.

**Comment by justxi** [comment]
You should sync you repo ;). roct-thunk-interface it not in this repo anymore. 

> The one from this overlay -- although it should be pointed out that it doesn't quite matter so much if the headers are in a subdirectory of /usr/include, as they will be found recursively beneath the hint path given to CMake.

Of course, but when it is in "/usr/include" it need no hint.
Please update this repo and rebuild as much as possible from the official Gentoo portage.

**Comment by justxi** [comment]
Pleae reopen if the problem still persist.
