### ISSUE TITLE
dev-util/rocm-clang-ocl-2.7.0 assumes binary rocm in /opt ?

### ISSUE THREAD

**Issue by hagar-dunor** [justxi/rocm#84]
Hi all

When building amd-rocm-meta (v2.7.0) with the opencl use flag, it pulls dev-util/rocm-clang-ocl which fails to build, see log.
[build.log](https://github.com/justxi/rocm/files/3638599/build.log)

From the logs it looks like CMakeLists.txt assumes rocm to be installed in /opt

++

**Comment by justxi** [comment]
Do you have "dev-util/rocm-cmake" installed?

**Comment by hagar-dunor** [comment]
I did not have it. One-shotting it allows rocm-clang-ocl and amd-rocm-meta to complete.
Missing dependency then.

**Comment by justxi** [comment]
So "rocm-clang-ocl" and "amd-rocm-meta" need "rocm-clang" as a dependency, right?

**Comment by justxi** [comment]
I added "rocm-cmake" only to "rocm-clang-ocl" because the packages which needs it should pull it in.
