### ISSUE TITLE
ROCm 2.8.0 has been released.

### ISSUE THREAD

**Issue by PowPingDone** [justxi/rocm#85]
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/releases/tag/roc-2.8.0
https://github.com/RadeonOpenCompute/ROCK-Kernel-Driver/releases/tag/roc-2.8.0
https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/releases/tag/roc-2.8.0
etc.

**Comment by justxi** [comment]
Yes I see. But these ebuilds are already in Gentoo portage.
Hopefully that the ROCm-OpenCL-Runtime will work on the systems of all testers to get it into the official portage.

**Comment by Lucretia** [comment]
Ijust pulled and they don't show, I just gentoo's git and they're not there.

**Comment by justxi** [comment]
Yes thats right, but I will not add any ebuilds to this repository which are already in portage. This would result in confusion. Currently "dev-libs/rocr-runtime" is not available as version 2.8 and testing which rocminfo-2.8 is not possible.

**Comment by Lucretia** [comment]
Yes that's fine, what I mean is, they're not in portage, I synched earlier and they're not there.

**Comment by justxi** [comment]
This is work in progress... currently not in portage... https://github.com/gentoo/gentoo/pull/10724

**Comment by justxi** [comment]
Here you find a list of changes I did to the ebuilds in portage:
https://github.com/gentoo/gentoo/pull/10724#issuecomment-536162116

**Comment by justxi** [comment]
@davidrohr and all others =)

I am currently preparing new ebuilds for ROCm 2.8...

**Comment by davidrohr** [comment]
I have seen it. So far i only created an rpm binary meta package and just opened a pr. Not working on more for now.

**Comment by justxi** [comment]
I updated all ebuilds (except rocALUTION) from this repository, happily the others did not need big changes.
Next step is to create PRs from my changes. I will create links to this issue, when I have created them.

**Comment by PowPingDone** [comment]
``dev-libs/rocm-comgr-2.8.0`` ebuild does not exist when it should. A world update: 
```
!!! The following update has been skipped due to unsatisfied dependencies:

dev-libs/rocm-opencl-runtime:0

  selected: (dev-libs/rocm-opencl-runtime-2.7.0:0/2.7::rocm, installed)
  skipped: (dev-libs/rocm-opencl-runtime-2.8.0:0/2.8::rocm, ebuild scheduled for merge) (see unsatisfied dependency below)

emerge: there are no ebuilds to satisfy ">=dev-libs/rocm-comgr-2.8.0".
(dependency required by "dev-libs/rocm-opencl-runtime-2.8.0::rocm" [ebuild])
```

**Comment by justxi** [comment]
The ebuilds which are already in portage are not updated till now... We are working on that...
I the meantime you could try this:
https://github.com/gentoo/gentoo/pull/10724#issuecomment-536162116

**Comment by justxi** [comment]
@PowPingDone The ebuild should be in portage now https://github.com/gentoo/gentoo/pull/10724#issuecomment-536614293

**Comment by justxi** [comment]
All ebuilds are either in portage or in this repo.
