### ISSUE TITLE
dev-libs/rocm-opencl-driver-2.7.9999 is broken

### ISSUE THREAD

**Issue by Lucretia** [justxi/rocm#86]
Tried to build this because the portage 2.7.0 won't link with llvm-roc-2.7.9999 (llvm-10) from this overlay.

The rocm-opencl-driver-2.6.0-install-header.patch fails to apply cleanly.

**Comment by Lucretia** [comment]
Seems the patches are no longer required.

**Comment by justxi** [comment]
The *.9999 are as you may expect in experimental state. Due to the fact that ROCM 2.8 seems to be rolled out, the *.9999 from this repo may not be up to date.

**Comment by Lucretia** [comment]
Builds with:

```
[ebuild   R    ] dev-libs/roct-thunk-interface-2.7.0:0/2.7::gentoo  0 KiB
[ebuild   R    ] dev-util/rocm-cmake-2.7.0::gentoo  0 KiB
[ebuild   R    ] dev-libs/rocr-runtime-2.7.0-r1:0/2.7::rocm  USE="-nonfree" 0 KiB
[ebuild   R   *] dev-libs/rocm-device-libs-9999:0/9999::rocm  0 KiB
[ebuild   R   *] dev-libs/rocm-opencl-driver-2.7.9999:0/2.7::rocm  USE="-test" 0 KiB
[ebuild   R    ] dev-util/rocm-smi-2.7.0::rocm  0 KiB
[ebuild   R    ] dev-util/rocminfo-2.7.0-r1:0/2.7::rocm  0 KiB
[ebuild   R    ] dev-libs/rocm-opencl-runtime-2.7.0:0/2.7::rocm  0 KiB
```

**Comment by justxi** [comment]
Did you change anything or should I change something?
Or simply create a PR is necessary.

**Comment by Lucretia** [comment]
Hmmm, seems you don't need to do anything.

**Comment by justxi** [comment]
Ok, then I close this issue.
