### ISSUE TITLE
rocm-opencl-runtime-2.0.0: .../runtime/device/rocm/libraries.amdgcn.inc:2:10: fatal error: oclc_correctly_rounded_sqrt_off.amdgcn.inc: No such file or directory  #include "oclc_correctly_rounded_sqrt_off.amdgcn.inc"

### ISSUE THREAD

**Issue by ernsteiswuerfel** [justxi/rocm#9]
[...]
In file included from /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/runtime/device/devprogram.cpp:16:0:
/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/runtime/device/rocm/libraries.amdgcn.inc:2:10: fatal error: oclc_correctly_rounded_sqrt_off.amdgcn.inc: No such file or directory
 #include "oclc_correctly_rounded_sqrt_off.amdgcn.inc"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [runtime/CMakeFiles/oclruntime.dir/build.make:351: runtime/CMakeFiles/oclruntime.dir/device/devprogram.cpp.o] Error 1
[rocm-opencl-runtime-2.0.0:20190124-164027.log](https://github.com/justxi/rocm/files/2793221/rocm-opencl-runtime-2.0.0.20190124-164027.log)
[...]

**Comment by justxi** [comment]
Yes, this is currently work in progress.
I am trying to solve this.

**Comment by justxi** [comment]
Linking and installing must be fixed.
But this issue seems to be fixed in the experimental ebuild, so I close this.

**Comment by ernsteiswuerfel** [comment]
Sorry but, still the same error with the the rocm-opencl-runtime-2.0.0 ebuild from 7 hours ago:

[...]
In file included from /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/runtime/device/devprogram.cpp:16:0:
/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/runtime/device/rocm/libraries.amdgcn.inc:2:10: fatal error: oclc_correctly_rounded_sqrt_off.amdgcn.inc: No such file or directory
 #include "oclc_correctly_rounded_sqrt_off.amdgcn.inc"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by justxi** [comment]
Yes you are right, when I run 
> "MAKEOPTS="-j1" emerge rocm-opencl-runtime
I get the same error. With "-j16" it works.

**Comment by ernsteiswuerfel** [comment]
Interesting! It doesn't work for me with -j16 either (I got an Opteron 6380, so I use -j16 regularly). I just used MAKEOPTS="-j1" to get a more clear error message.

**Comment by justxi** [comment]
So what is your latest error message? The same as above or somthing like missing libraries "-clang..."?

**Comment by justxi** [comment]
Can you provide your current error?

**Comment by ernsteiswuerfel** [comment]
-rw-r--r-- 1 root root 2,8K 30. Jan 02:36 rocm-opencl-runtime-2.0.0.ebuild
[rocm-opencl-runtime-2.0.0:20190201-123624.log](https://github.com/justxi/rocm/files/2821572/rocm-opencl-runtime-2.0.0.20190201-123624.log)


Current error is:
[...]
In file included from /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/ROCm-OpenCL-Runtime-roc-2.0.0/runtime/device/devprogram.cpp:16:0:
/var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/runtime/device/rocm/libraries.amdgcn.inc:2:10: fatal error: oclc_correctly_rounded_sqrt_off.amdgcn.inc: No such file or directory
 #include "oclc_correctly_rounded_sqrt_off.amdgcn.inc"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by justxi** [comment]
Can you run the latest version of the rocm-opencl-runtime ebuild?
For me it run til 97%, there are still missing libraries, but I you reach also this point, I have a closer idea where to look for the problem.

**Comment by justxi** [comment]
There is an updated ebuild, please try it.

**Comment by ernsteiswuerfel** [comment]
Success, the latest ebuild builds flawlessly! Many thanks for your efforts!

However I got another problem now. eselect can't find the newly installed opencl runtime:
```
# eselect opencl list
Available OpenCL implementations:
  [1]   ocl-icd *
# ls -alh OpenCL/vendors/
insgesamt 0
drwxr-xr-x 1 root root  14  3. Feb 12:14 .
drwxr-xr-x 1 root root  26 15. Jan 2018  ..
drwxr-xr-x 1 root root 102 28. Dez 22:17 ocl-icd
```

**Comment by justxi** [comment]
Yes, that must be solved by installing the files to the correct path.

**Comment by justxi** [comment]
Now the libraries install to the correct directories, but running "clinfo" I get a "segfault".
Please try it. I close this issue because I think we have a solution.

**Comment by ernsteiswuerfel** [comment]
Posting here again as the newest ebuild unfortunately fails to build:

```
[...]
Scanning dependencies of target googletest
[  0%] Creating directories for 'googletest'
[  0%] Performing download step (git clone) for 'googletest'
-- googletest download command succeeded.  See also /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/compiler/driver/src/unittest/googletest-prefix/src/googletest-stamp/googletest-download-*.log
[  0%] No patch step for 'googletest'
[  0%] Performing update step for 'googletest'
Current branch master is up to date.
[  0%] Performing configure step for 'googletest'
-- googletest configure command succeeded.  See also /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/compiler/driver/src/unittest/googletest-prefix/src/googletest-stamp/googletest-configure-*.log
[  0%] Performing build step for 'googletest'
-- googletest build command succeeded.  See also /var/tmp/portage/dev-libs/rocm-opencl-runtime-2.0.0/work/build/compiler/driver/src/unittest/googletest-prefix/src/googletest-stamp/googletest-build-*.log
[  1%] No install step for 'googletest'
[  1%] Completed 'googletest'
[  1%] Built target googletest
Scanning dependencies of target roc-cl-unittest
[  1%] Building CXX object compiler/driver/src/unittest/CMakeFiles/roc-cl-unittest.dir/Tests.cpp.o
[  2%] Linking CXX executable roc-cl-unittest
/usr/lib/gcc/x86_64-pc-linux-gnu/7.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lgtest
/usr/lib/gcc/x86_64-pc-linux-gnu/7.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lgtest_main
collect2: error: ld returned 1 exit status
make[2]: *** [compiler/driver/src/unittest/CMakeFiles/roc-cl-unittest.dir/build.make:148: compiler/driver/src/unittest/roc-cl-unittest] Error 1
make[1]: *** [CMakeFiles/Makefile2:276: compiler/driver/src/unittest/CMakeFiles/roc-cl-unittest.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
 * ERROR: dev-libs/rocm-opencl-runtime-2.0.0::rocm failed (compile phase):
 *   (no error message)
```
[rocm-opencl-runtime-2.0.0:20190203-222545.log](https://github.com/justxi/rocm/files/2826107/rocm-opencl-runtime-2.0.0.20190203-222545.log)

**Comment by justxi** [comment]
Strange, I didn´t changed anything in the build phase.

**Comment by stalkerg** [comment]
Yep, I forgot to say - you forgot to add gtest dependency.

**Comment by ernsteiswuerfel** [comment]
Ah I see. thanks!. Must have been doing an emerge --depclean meanwhile... If it's a dependency, it probably should be pulled in by the ebuild.

Anyway, with gtest emerged rocm-opencl-runtime-2.0.0 builds fine again! clinfo-2.2.18.04.06 works too and shows reasonable data for my RX 580.

**Comment by justxi** [comment]
I will add the dependencies later.
Good to hear that it works for you. I still get a segfault while running clinfo. 
Which Linux kernel do you use?

**Comment by ernsteiswuerfel** [comment]
gentoo-sources-4.19.19.

**Comment by stalkerg** [comment]
> I still get a segfault while running clinfo.

I have addr error (looks like something in LLVM) but I should try again. (I have Vega56)

**Comment by justxi** [comment]
I have added the dependency. Hopefully I can finally close this.
Fore the LLVM problem we should proceed in https://github.com/justxi/rocm/issues/18
