### ISSUE TITLE
rocBLAS memory requirement

### ISSUE THREAD

**Issue by ChrisHad** [justxi/rocm#99]
Hi, thanks for the great work!
I was trying to build rocBLAS and realised it requires a lot of memory. From this [issue](https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/664) I used the flag `-lasm_ci` for building with 16GB RAM + 16 GB swapfile:  

Can a use flag be added to enable the corresponding cmake flag `-DTensile_LOGIC="asm_ci"`?

**Comment by justxi** [comment]
I have added a use flag: https://github.com/justxi/rocm/blob/master/sci-libs/rocBLAS/rocBLAS-2.9.0-r1.ebuild

Please test if it works.

**Comment by ChrisHad** [comment]
Just tested and it works.
Thanks,
Chris
